// C12 — Oficina de Pintura: 12 padrões vetoriais + código offline com checksum.
const PATTERNS=['FAIXA CENTRAL','FAIXAS DUPLAS','LATERAIS','DIAGONAL','CHEVRON','CHAMAS','XADREZ','GRADIENTE','BLOCOS SPEED','RAIO','MEIO A MEIO','ONDA'];
const SPONSORS=['HORIZON ZERO','NEON FUEL','VALE TURBO','ZERO LABS','PIXEL OIL','SERRA TECH','PIT 27','NOVA GRIP'];
const HEX=/^#[0-9a-f]{6}$/i;let editingCar=0;
function hex(v,f='#ffffff'){v=String(v||'').trim();return HEX.test(v)?v.toLowerCase():f;}
function layer(v,i=0){const raw=v&&v.pattern!==undefined?v.pattern:i;return{pattern:Math.max(-1,Math.min(11,Math.floor(Number(raw)))),color:hex(v&&v.color,['#111111','#ff3b30','#38d5ff'][i]||'#fff')};}
function clean(v={}){return{active:v.active!==false,base:hex(v.base,'#ffcc00'),layers:[layer(v.layers&&v.layers[0],0),layer(v.layers&&v.layers[1],-1),layer(v.layers&&v.layers[2],-1)],number:Math.max(0,Math.min(99,Math.floor(Number(v.number)||0))),sponsor:Math.max(0,Math.min(SPONSORS.length-1,Math.floor(Number(v.sponsor)||0)))};}
function stock(id){const c=CARS[id]||CARS[0],b=CAR_SKINS[c.id]||[c.color,c.stripe];return clean({base:b[0],layers:[{pattern:0,color:b[1]},{pattern:-1,color:'#ff3b30'},{pattern:-1,color:'#38d5ff'}],number:(id+1)*7%100,sponsor:id%SPONSORS.length});}
function rgb(h){const n=parseInt(hex(h).slice(1),16);return[(n>>16)&255,(n>>8)&255,n&255];}function rh(r,g,b){return'#'+[r,g,b].map(v=>(v|0).toString(16).padStart(2,'0')).join('');}
function fnv(a){let h=2166136261;for(const b of a){h^=b;h=Math.imul(h,16777619)>>>0;}return h>>>0;}function put32(a,n){a.push(n&255,n>>>8&255,n>>>16&255,n>>>24&255);}function get32(b,o){return(b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;}
function b64(a){let s='';for(const b of a)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}function ub64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0));}
function encode(input){const v=clean(input),a=[1,...rgb(v.base)];for(const l of v.layers)a.push(l.pattern<0?255:l.pattern,...rgb(l.color));a.push(v.number,v.sponsor);const body=Uint8Array.from(a),out=[...body];put32(out,fnv(body));return'RRP1-'+b64(Uint8Array.from(out));}
function decode(code){const t=String(code||'').trim();if(!/^RRP1-/i.test(t))throw Error('CÓDIGO INVÁLIDO');const b=ub64(t.slice(5));if(b.length!==22||b[0]!==1)throw Error('FORMATO INVÁLIDO');if(fnv(b.subarray(0,18))!==get32(b,18))throw Error('CHECKSUM INVÁLIDO');let o=1,base=rh(b[o++],b[o++],b[o++]),layers=[];for(let i=0;i<3;i++){const p=b[o++];layers.push({pattern:p===255?-1:Math.min(11,p),color:rh(b[o++],b[o++],b[o++])});}return clean({base,layers,number:b[o++],sponsor:b[o++]});}
function form(){return clean({base:paintBase.value,number:paintNumber.value,sponsor:paintSponsor.value,layers:[0,1,2].map(i=>({pattern:Number(document.getElementById('paintPattern'+i).value),color:document.getElementById('paintColor'+i).value}))});}
function setForm(v){v=clean(v);paintBase.value=v.base;paintNumber.value=v.number;paintSponsor.value=v.sponsor;for(let i=0;i<3;i++){document.getElementById('paintPattern'+i).value=v.layers[i].pattern;document.getElementById('paintColor'+i).value=v.layers[i].color;}paintCode.value=encode(v);drawPaintPreview(v);}
function status(t,c='#38d5ff'){paintStatus.textContent=t;paintStatus.style.color=c;}function opts(){const h=['<option value="-1">SEM CAMADA</option>',...PATTERNS.map((x,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} · ${x}</option>`)].join('');for(let i=0;i<3;i++)document.getElementById('paintPattern'+i).innerHTML=h;paintSponsor.innerHTML=SPONSORS.map((x,i)=>`<option value="${i}">${x}</option>`).join('');}
globalThis.drawPaintPreview=function drawPaintPreview(v=form()){const c=paintPreviewCanvas,g=c.getContext('2d'),w=c.width,h=c.height,car=CARS[editingCar]||CARS[0];g.imageSmoothingEnabled=false;const bg=g.createLinearGradient(0,0,0,h);bg.addColorStop(0,'#281154');bg.addColorStop(.48,'#10152f');bg.addColorStop(.49,'#181818');bg.addColorStop(1,'#050505');g.fillStyle=bg;g.fillRect(0,0,w,h);g.fillStyle='#30333c';g.fillRect(w*.24,h*.62,w*.52,h*.38);drawCarGeneric(g,w/2,h*.82,160,v.base,true,.12,{model:car.model,stripe:v.layers[0].color,livery:v,damage:0,upgradeVisuals:career.upgrades},true);};
globalThis.paintShopLiveryFor=id=>carLivery(id);globalThis.paintShopSponsorName=i=>SPONSORS[Math.max(0,Math.min(SPONSORS.length-1,Number(i)||0))];globalThis.paintShopEncode=encode;globalThis.paintShopDecode=decode;
globalThis.openPaintShop=function openPaintShop(){editingCar=garageCarView;opts();const v=carLivery(editingCar)||stock(editingCar);setForm(v);paintCarName.textContent=(CARS[editingCar]||CARS[0]).name.toUpperCase();status('EDIÇÃO LOCAL · PERFORMANCE INALTERADA');gameMode='paint';showMenu('paint');};
globalThis.paintShopSave=function paintShopSave(){career.liveries[editingCar]=clean(form());career.flags.c12Paint=true;saveCareer();playSFX('buy');status('PINTURA SALVA NO CARRO','#55ff55');renderGarage();return career.liveries[editingCar];};
globalThis.paintShopImport=function paintShopImport(){try{const v=decode(paintCode.value);setForm(v);status('CÓDIGO IMPORTADO · SALVE PARA APLICAR','#55ff55');return v;}catch(e){status(e.message,'#ff4b4b');return null;}};
globalThis.paintShopCopy=async function paintShopCopy(){const c=encode(form());paintCode.value=c;try{await navigator.clipboard?.writeText(c);status('CÓDIGO COPIADO · '+c.length+' CARACTERES','#55ff55');}catch(e){status('SELECIONE E COPIE O CÓDIGO','#ffcc00');}return c;};
globalThis.paintShopShare=async function paintShopShare(){const c=encode(form());try{if(navigator.share)await navigator.share({title:'Retrô Racer · Pintura',text:'Minha pintura Retrô Racer: '+c});else await paintShopCopy();}catch(e){if(e.name!=='AbortError')await paintShopCopy();}return c;};
globalThis.paintShopSnapshot=()=>({patterns:PATTERNS.length,sponsors:SPONSORS.length,car:editingCar,livery:clean(form()),saved:carLivery(editingCar),code:encode(form())});
function wire(){btnPaintShop.onclick=openPaintShop;['paintBase','paintNumber','paintSponsor','paintPattern0','paintColor0','paintPattern1','paintColor1','paintPattern2','paintColor2'].forEach(id=>document.getElementById(id).addEventListener('input',()=>drawPaintPreview()));btnPaintSave.onclick=paintShopSave;btnPaintImport.onclick=paintShopImport;btnPaintCopy.onclick=paintShopCopy;btnPaintShare.onclick=paintShopShare;btnPaintReset.onclick=()=>{setForm(stock(editingCar));status('RASCUNHO STOCK RESTAURADO');};btnPaintBack.onclick=()=>{renderGarage();showMenu('garage');};}wire();window.RRCore.paintShop={PATTERNS,SPONSORS,clean,encode,decode,stock};
