// OURO 9 — FENDA: roguelite determinístico de 5 pistas, sem servidor.
const N=(id,name,desc,mods={},tags=[])=>Object.freeze({id,name,desc,mods:Object.freeze(mods),tags:Object.freeze(tags),legendary:false});
const L=(id,name,desc,mods={},tags=[])=>Object.freeze({id,name,desc,mods:Object.freeze(mods),tags:Object.freeze(tags),legendary:true});
const CARDS=Object.freeze([
N('hot','MOTOR QUENTE','+8% velocidade · +30% consumo',{speed:1.08,fuelUse:1.30,reward:1.08},['speed','risk']),N('scraped','PNEU RASPADO','-15% grip · +50% banco',{grip:.85,reward:1.50},['risk','reward']),N('leak','TANQUE FURADO','consumo brutal · nitro infinito',{fuelUse:1.55,nitroInfinite:true,reward:1.15},['fuel','nitro','risk']),N('dirty','CONTRATO SUJO','GHOST mais forte · banco x2',{ghostBoost:1.08,reward:2},['ghost','reward','risk']),N('fog','NEBLINA','visão curta · rivais também sofrem',{weather:'fog',ai:.94,reward:1.25},['weather','reward']),N('wildturbo','TURBINA LOUCA','nitro +35% · dano +15%',{nitro:1.35,damage:1.15,reward:1.12},['nitro','risk']),
N('handbrake','FREIO DE MÃO','grip +12% · velocidade -4%',{grip:1.12,speed:.96},['grip']),N('shortwing','ASA CURTA','velocidade +5% · grip -5%',{speed:1.05,grip:.95},['speed','risk']),N('highwing','ASA ALTA','grip +12% · velocidade -3%',{grip:1.12,speed:.97},['grip']),N('rich','MISTURA RICA','aceleração +10% · consumo +20%',{accel:1.10,fuelUse:1.20},['fuel','accel']),N('lean','MISTURA POBRE','consumo -22% · velocidade -3%',{fuelUse:.78,speed:.97},['fuel']),N('light','CHASSI LEVE','velocidade +5% · dano +30%',{speed:1.05,damage:1.30,reward:1.10},['speed','risk']),
N('armor','BLINDAGEM','dano -30% · velocidade -5%',{damage:.70,speed:.95},['armor']),N('draftmag','MAGNETO DE VÁCUO','draft +50% · grip -3%',{draft:1.50,grip:.97},['draft']),N('nopit','BOX PROIBIDO','pit não abastece · banco +35%',{pitDisabled:true,reward:1.35},['risk','reward']),N('reserve','RESERVA CLANDESTINA','+18% combustível imediato',{fuelBonus:.18},['fuel']),N('coldblood','SANGUE FRIO','dano -10% · banco +15%',{damage:.90,reward:1.15},['armor','reward']),N('slick','SLICK EXTREMO','grip +10% · chuva força respeito',{grip:1.10,wetPenalty:.84,reward:1.08},['grip','weather']),
N('sink','HEAT SINK','nitro +15% · consumo +5%',{nitro:1.15,fuelUse:1.05},['nitro']),N('fragile','NITRO FRÁGIL','nitro +30% · dano +20%',{nitro:1.30,damage:1.20,reward:1.12},['nitro','risk']),N('rex','REX SOLTO','IA +4% · banco +20%',{ai:1.04,reward:1.20},['ai','reward']),N('blindhud','SEM INSTRUMENTOS','HUD de corrida reduzido · banco +25%',{hudMinimal:true,reward:1.25},['risk','reward']),N('rain','CHUVA FORÇADA','pista molhada · banco +30%',{weather:'rain',reward:1.30},['weather','reward']),N('cold','PNEUS FRIOS','grip -10% · aceleração +8%',{grip:.90,accel:1.08},['grip','accel','risk']),
N('shortgear','CÂMBIO CURTO','aceleração +12% · final -6%',{accel:1.12,speed:.94},['accel']),N('longgear','CÂMBIO LONGO','final +10% · aceleração -6%',{speed:1.10,accel:.94},['speed']),N('draft2','VÁCUO DUPLO','draft +70% · banco -10%',{draft:1.70,reward:.90},['draft']),N('dirtyline','LINHA SUJA','grip -8% · banco +35%',{grip:.92,reward:1.35},['risk','reward']),N('eco','MOTOR CONSERVADOR','consumo -28% · final -4%',{fuelUse:.72,speed:.96},['fuel']),N('livechassis','CHASSI VIVO','grip +5% · dano +10% · banco +10%',{grip:1.05,damage:1.10,reward:1.10},['grip','risk']),
N('hardbody','CORPO FECHADO','dano -20% · aceleração -4%',{damage:.80,accel:.96},['armor']),N('jackpot','JACKPOT','banco +70% · consumo +15%',{reward:1.70,fuelUse:1.15},['reward','risk']),N('nonitro','SEM NITRO','nitro bloqueado · banco +45%',{nitroDisabled:true,reward:1.45},['risk','reward']),N('storm','TEMPESTADE','storm forçada · banco +40%',{weather:'storm',reward:1.40},['weather','risk','reward']),N('ghostline','LINHA DO GHOST','grip +6% · GHOST +6%',{grip:1.06,ghostBoost:1.06,reward:1.18},['ghost','grip']),N('razor','FIO DA NAVALHA','velocidade +7% · dano +18%',{speed:1.07,damage:1.18,reward:1.15},['speed','risk']),
L('eclipse','ECLIPSE CORE','speed/accel/grip +12% · banco +25%',{speed:1.12,accel:1.12,grip:1.12,reward:1.25},['legendary','speed']),L('redline','REDLINE INFINITO','nitro infinito · final +6% · consumo +25%',{nitroInfinite:true,speed:1.06,fuelUse:1.25},['legendary','nitro']),L('mirror','ESPELHO NEGRO','GHOST +12% · banco x2.2',{ghostBoost:1.12,reward:2.20},['legendary','ghost','reward']),L('zero','ZERO GRAVITY','grip +12% · final +8% · draft +25%',{grip:1.12,speed:1.08,draft:1.25,reward:1.20},['legendary','grip','speed'])
]);
const NORMAL=CARDS.filter(c=>!c.legendary),LEG=CARDS.filter(c=>c.legendary);let cachedMods=null;
function h32(x){x|=0;x=Math.imul(x^(x>>>16),0x45d9f3b);x=Math.imul(x^(x>>>16),0x45d9f3b);return (x^(x>>>16))>>>0;}
function seedFromDate(){const d=Number(localDateKey().replaceAll('-',''));return h32(d+((career.stats.riftRuns||0)+1)*0x9e3779b1+career.selectedCar*997);}
function pick(seed,n){return h32(seed+n*0x6d2b79f5);}
function ensureF(){career.fenda=career.fenda||{};return career.fenda;}
function generateLevels(seed){const max=Math.max(27,Math.min(999,career.level));const out=[];let x=seed;for(let i=0;i<5;i++){x=pick(x,i+1);let v=1+(x%max);while(out.includes(v))v=v>=max?1:v+1;out.push(v);}return out;}
function resetMods(){cachedMods={speed:1,accel:1,grip:1,fuelUse:1,damage:1,reward:1,nitro:1,draft:1,ai:1,ghostBoost:1,weather:'',pitDisabled:false,nitroInfinite:false,nitroDisabled:false,hudMinimal:false,wetPenalty:1,synergies:[]};}
function recompute(){resetMods();const chosen=ensureF().chosen||[],tags={};for(const id of chosen){const c=CARDS.find(x=>x.id===id);if(!c)continue;const m=c.mods;for(const k of ['speed','accel','grip','fuelUse','damage','reward','nitro','draft','ai','ghostBoost','wetPenalty'])if(m[k]!=null)cachedMods[k]*=m[k];for(const k of ['pitDisabled','nitroInfinite','nitroDisabled','hudMinimal'])if(m[k])cachedMods[k]=true;if(m.weather)cachedMods.weather=m.weather;for(const t of c.tags)tags[t]=(tags[t]||0)+1;}
 if((tags.speed||0)>=2){cachedMods.speed*=1.03;cachedMods.synergies.push('REDLINE');}if((tags.fuel||0)>=2){cachedMods.fuelUse*=.90;cachedMods.synergies.push('ECONOMIA');}if((tags.grip||0)>=2){cachedMods.grip*=1.04;cachedMods.synergies.push('TRILHO');}if((tags.risk||0)>=3){cachedMods.reward*=1.12;cachedMods.synergies.push('APOSTADOR');}if(cachedMods.nitroInfinite&&cachedMods.fuelUse>1.2){cachedMods.reward*=1.15;cachedMods.synergies.push('FUSÍVEL CURTO');}return cachedMods;}
globalThis.riftModifierSnapshot=function riftModifierSnapshot(){return cachedMods||recompute();};
globalThis.riftNitroInfinite=function riftNitroInfinite(){const m=riftModifierSnapshot();return !!m.nitroInfinite;};globalThis.riftNitroDisabled=function riftNitroDisabled(){return !!riftModifierSnapshot().nitroDisabled;};globalThis.riftPitDisabled=function riftPitDisabled(){return !!riftModifierSnapshot().pitDisabled;};
function generateChoices(){const f=ensureF(),stage=f.stage,base=f.seed+stage*911,ids=[];for(let i=0;i<3;i++){let c=NORMAL[pick(base,i)%NORMAL.length],guard=0;while((ids.includes(c.id)||f.chosen.includes(c.id))&&guard++<NORMAL.length)c=NORMAL[(NORMAL.indexOf(c)+1)%NORMAL.length];ids.push(c.id);}if(stage===f.legendaryStage){const l=LEG[pick(f.seed,77)%LEG.length];ids[2]=l.id;}f.choices=ids;saveCareer();return ids;}
globalThis.riftStartRun=function riftStartRun(){if(career.fenda?.active)return false;const f=career.fenda={...structuredClone(defaultCareer.fenda)};f.active=true;f.seed=seedFromDate();f.stage=0;f.levels=generateLevels(f.seed);f.fuel=1;f.preDamage=Number(career.carDamage[currentCar().id]||0);f.damage=f.preDamage;f.bank=0;f.chosen=[];f.choices=[];f.legendaryStage=f.seed%4;f.stageDone=false;f.completed=false;f.failed=false;career.stats.riftRuns=(career.stats.riftRuns||0)+1;career.flags.c09Rift=true;cachedMods=null;saveCareer();return true;};
globalThis.riftAbort=function riftAbort(reason='FENDA ABANDONADA'){const f=ensureF();if(!f.active)return;career.carDamage[currentCar().id]=f.preDamage||0;f.active=false;f.failed=true;f.lastResult=reason;f.bank=0;cachedMods=null;document.body.classList.remove('rift-minimal-hud');saveCareer();};
globalThis.riftFail=function riftFail(reason='RUN ENCERRADA'){const f=ensureF();if(!f.active)return;career.stats.riftBestStage=Math.max(career.stats.riftBestStage||0,f.stage+1);career.carDamage[currentCar().id]=f.preDamage||0;f.active=false;f.failed=true;f.lastResult=reason;f.bank=0;cachedMods=null;document.body.classList.remove('rift-minimal-hud');saveCareer();};
globalThis.riftApplyRaceStart=function riftApplyRaceStart(){const f=ensureF();if(!f.active||raceContext.mode!=='rift')return;recompute();const mods=calcMods();fuel=MathUtils.limit(f.fuel*mods.fuelCapacity,0,mods.fuelCapacity);career.carDamage[currentCar().id]=MathUtils.limit(f.damage,0,1);if(cachedMods.weather)runtimeWeather=cachedMods.weather;document.body.classList.toggle('rift-minimal-hud',cachedMods.hudMinimal);if(cachedMods.ghostBoost>1){const g=cars.find(c=>c.name==='GHOST');if(g)g.baseSpeed*=cachedMods.ghostBoost;}saveCareer();};
globalThis.riftStageFinish=function riftStageFinish(rank,basePrize){const f=ensureF();if(!f.active||raceContext.mode!=='rift')return 0;const m=recompute(),mods=calcMods();f.fuel=MathUtils.limit(fuel/Math.max(.001,mods.fuelCapacity),0,1);f.damage=MathUtils.limit(career.carDamage[currentCar().id]||0,0,1);const earned=Math.round(Math.max(0,basePrize)*m.reward);f.bank+=earned;f.stageDone=true;career.stats.riftBestStage=Math.max(career.stats.riftBestStage||0,f.stage+1);if(f.stage>=4){career.money+=f.bank;career.stats.earned+=f.bank;career.stats.riftWins=(career.stats.riftWins||0)+1;career.carDamage[currentCar().id]=f.preDamage||0;f.completed=true;f.active=false;f.lastResult=`FENDA CONCLUÍDA · ${money(f.bank)}`;const total=f.bank;cachedMods=null;document.body.classList.remove('rift-minimal-hud');saveCareer();return total;}generateChoices();saveCareer();return earned;};
globalThis.riftChooseCard=function riftChooseCard(id){const f=ensureF();if(!f.active||!f.stageDone||!f.choices.includes(id))return false;const card=CARDS.find(c=>c.id===id);if(!card)return false;f.chosen.push(id);if(card.mods.fuelBonus)f.fuel=MathUtils.limit(f.fuel+card.mods.fuelBonus,0,1);f.stage++;f.stageDone=false;f.choices=[];cachedMods=null;recompute();saveCareer();return true;};
globalThis.riftBeginCurrentRace=function riftBeginCurrentRace(){const f=ensureF();if(!f.active)return false;raceContext={mode:'rift',selectedLevel:f.levels[f.stage],replay:false,laps:1,dailySeed:f.seed,ghost:false,boss:false,insurance:false};openPreRace(raceContext.selectedLevel,'rift');return true;};
globalThis.riftAfterResult=function riftAfterResult(){const f=ensureF();if(f.completed||!f.active){openRift();return;}openRift();};
function cardHtml(id){const c=CARDS.find(x=>x.id===id);if(!c)return'';return `<button class="rift-card ${c.legendary?'legendary':''}" data-rift-card="${c.id}"><span>${c.legendary?'★ LENDÁRIA':'CARTA'}</span><b>${c.name}</b><em>${c.desc}</em></button>`;}
globalThis.renderRift=function renderRift(){const f=ensureF(),status=document.getElementById('riftStatus'),tracks=document.getElementById('riftTracks'),cards=document.getElementById('riftCards'),mods=document.getElementById('riftMods'),start=document.getElementById('btnRiftStart');if(!status)return;const m=recompute();status.innerHTML=f.active?`RUN ${f.stage+1}/5 · BANCO <b>${money(f.bank)}</b> · GAS ${Math.round(f.fuel*100)}% · DANO ${Math.round(f.damage*100)}%`:(f.completed?`<b>FENDA CONCLUÍDA</b> · ${f.lastResult}`:f.failed?`<b>RUN PERDIDA</b> · ${f.lastResult}`:'5 PISTAS · 1 VIDA · ~9 MIN');tracks.innerHTML=(f.levels||[]).map((lv,i)=>`<span class="rift-track ${i===f.stage&&f.active?'active':''} ${i<f.stage?'done':''}">${i+1}<b>${lv}</b></span>`).join('');mods.textContent=f.active?`CARTAS ${f.chosen.length} · ${m.synergies.length?'SINERGIAS '+m.synergies.join(' / '):'SEM SINERGIA AINDA'}`:'DANO E COMBUSTÍVEL ATRAVESSAM AS 5 PISTAS';if(f.active&&f.stageDone){cards.innerHTML=f.choices.map(cardHtml).join('');cards.querySelectorAll('[data-rift-card]').forEach(b=>b.onclick=()=>{if(riftChooseCard(b.dataset.riftCard)){renderRift();riftBeginCurrentRace();}});start.classList.add('hidden');}else{cards.innerHTML='';start.classList.remove('hidden');start.textContent=f.active?'🏁 ENTRAR NA PISTA '+(f.stage+1):'⚡ INICIAR NOVA FENDA';start.onclick=()=>{if(!f.active)riftStartRun();renderRift();riftBeginCurrentRace();};}};
globalThis.openRift=function openRift(){gameMode='riftmenu';renderRift();showMenu('rift');};
globalThis.RR_RIFT_CARDS=CARDS;
if(career&&career.flags&&!career.flags.c09Rift){career.flags.c09Rift=true;saveCareer();}
