// OURO 10 — TEMPORADA HORIZONTE: live ops offline, determinístico por data.
const EPOCH=Date.UTC(2026,0,1)/86400000;
const MODIFIERS=Object.freeze([
 {id:'redline',name:'SEMANA REDLINE',desc:'+4% final · +10% consumo',speed:1.04,fuelUse:1.10,ai:1.01},
 {id:'grip',name:'TRILHO MAGNÉTICO',desc:'+7% grip · rivais +2%',grip:1.07,ai:1.02},
 {id:'storm',name:'FRENTE DE TEMPESTADE',desc:'chuva em todas as provas · prêmio de XP +10%',weather:'rain',xp:1.10},
 {id:'eco',name:'COPA ECONOMIA',desc:'-18% consumo · nitro -8%',fuelUse:.82,nitro:.92},
 {id:'ghost',name:'CAÇADA AO GHOST',desc:'rivais +3% · XP +15%',ai:1.03,xp:1.15},
 {id:'fragile',name:'VIDRO E AÇO',desc:'+5% final · dano +20%',speed:1.05,damage:1.20,xp:1.12},
 {id:'turbo',name:'TURBO FEST',desc:'nitro +18% · consumo +8%',nitro:1.18,fuelUse:1.08},
 {id:'precision',name:'LINHA PERFEITA',desc:'+5% grip · draft +12%',grip:1.05,draft:1.12}
]);
function dayNo(key=localDateKey()){const [y,m,d]=String(key).split('-').map(Number);return Math.floor(Date.UTC(y,m-1,d)/86400000);}
function mix(x){x|=0;x=Math.imul(x^(x>>>16),0x45d9f3b);x=Math.imul(x^(x>>>16),0x45d9f3b);return(x^(x>>>16))>>>0;}
function imod(n,m){return((n%m)+m)%m;}
function descriptor(key=localDateKey()){const dn=dayNo(key),rel=dn-EPOCH,index=Math.floor(rel/28),day=imod(rel,28),week=Math.floor(day/7),seasonKey=`HZ-${String(index+1).padStart(4,'0')}`,seed=mix(index*0x9e3779b1+0x51ea50),mod=MODIFIERS[seed%MODIFIERS.length],daily=1+(mix(dn^seed)%999),weekSeed=mix(seed+week*0x6d2b79f5),levels=[];let x=weekSeed;for(let i=0;i<3;i++){x=mix(x+i+1);let lv=1+x%999;while(levels.includes(lv))lv=lv>=999?1:lv+1;levels.push(lv);}return{key:seasonKey,index,day,week,dayNumber:dn,modifier:mod,dailyLevel:daily,weeklyLevels:levels,weekKey:`${seasonKey}-W${week+1}`,daysLeft:27-day};}
// JS não aceita literal 0x51ea50; substituído abaixo por inteiro estável.

function ensureSeason(){const d=descriptor(),s=career.season;if(s.key!==d.key){if(s.key)s.history=[...(s.history||[]),{key:s.key,xp:s.xp,passLevel:s.passLevel}].slice(-4);s.key=d.key;s.xp=0;s.passLevel=0;s.daily={};s.weekly={};s.gauntlet={key:'',stage:0,levels:[],active:false,score:0};career.flags.c10Season=true;saveCareer();}return d;}
function passReward(level){return level%10===0?100:level%5===0?50:15;}
function awardXp(raw){const d=ensureSeason(),m=d.modifier,xp=Math.max(0,Math.round(raw*(m.xp||1))),s=career.season,old=s.passLevel;s.xp+=xp;s.passLevel=Math.min(40,Math.floor(s.xp/100));let fichas=0;for(let lv=old+1;lv<=s.passLevel;lv++)fichas+=passReward(lv);if(fichas){career.fichas=(career.fichas||0)+fichas;career.stats.fichasEarned=(career.stats.fichasEarned||0)+fichas;}saveCareer();return{xp,fichas,levels:s.passLevel-old};}
function pointsForRank(rank){return rank===1?100:rank===2?80:rank===3?65:rank<=8?45:30;}
function dailyKey(){return localDateKey();}
function weeklyEntry(){const d=ensureSeason(),s=career.season;s.weekly[d.weekKey]=s.weekly[d.weekKey]||{bestScore:0,pointsAwarded:0,bestTime:0};return s.weekly[d.weekKey];}
function shadowBoard(d){const rows=[];const own=career.season.daily[dailyKey()];if(own&&own.bestTime>0)rows.push({alias:'VOCÊ',time:own.bestTime,car:currentCar().name,own:true});for(const entry of career.shadow.library||[])for(const g of entry.ghosts||[])if(Number(g.level)===d.dailyLevel&&Number(g.lapTime)>0)rows.push({alias:g.alias||'SOMBRA',time:Number(g.lapTime),car:CARS[g.car]?.name||'CARRO',own:false});rows.sort((a,b)=>a.time-b.time);return rows.slice(0,8);}
function renderPass(){const el=document.getElementById('seasonPass');if(!el)return;const lv=career.season.passLevel,xp=career.season.xp;el.innerHTML=Array.from({length:40},(_,i)=>{const n=i+1,done=n<=lv,next=n===lv+1;return `<span class="season-pass-node ${done?'done':''} ${next?'next':''}"><b>${n}</b><em>${passReward(n)}F</em></span>`;}).join('');document.getElementById('seasonXp').textContent=`PASSE ${lv}/40 · ${xp%100}/100 XP`;}
function renderBoard(d){const box=document.getElementById('seasonBoard'),rows=shadowBoard(d);box.innerHTML=rows.length?rows.map((r,i)=>`<div class="season-rank ${r.own?'own':''}"><b>${i+1}º</b><span>${r.alias}</span><em>${formatTime(r.time)}</em></div>`).join(''):'<div class="muted center">Importe Códigos de Sombra da pista destaque para preencher o placar.</div>';}
globalThis.seasonModifierSnapshot=function seasonModifierSnapshot(){if(!raceContext||!['seasonDaily','seasonGauntlet'].includes(raceContext.mode))return null;return ensureSeason().modifier;};
globalThis.seasonCurrent=ensureSeason;
globalThis.seasonStartDaily=function seasonStartDaily(){const d=ensureSeason();raceContext={mode:'seasonDaily',selectedLevel:d.dailyLevel,replay:false,laps:3,dailySeed:`${d.key}|D${d.day+1}`,ghost:false,boss:false,insurance:false,weatherOverride:d.modifier.weather||null};openPreRace(d.dailyLevel,'seasonDaily');};
globalThis.seasonStartGauntlet=function seasonStartGauntlet(){const d=ensureSeason(),g=career.season.gauntlet;if(!g.active||g.key!==d.weekKey){career.season.gauntlet={key:d.weekKey,stage:0,levels:[...d.weeklyLevels],active:true,score:0};saveCareer();}const a=career.season.gauntlet;raceContext={mode:'seasonGauntlet',selectedLevel:a.levels[a.stage],replay:false,laps:1,dailySeed:`${d.weekKey}|${a.stage}`,ghost:false,boss:false,insurance:false,weatherOverride:d.modifier.weather||null};openPreRace(raceContext.selectedLevel,'seasonGauntlet');};
globalThis.seasonRaceFinish=function seasonRaceFinish(rank,totalTime){if(!raceContext||!['seasonDaily','seasonGauntlet'].includes(raceContext.mode))return null;const d=ensureSeason(),base=pointsForRank(rank),s=career.season;if(raceContext.mode==='seasonDaily'){const k=dailyKey(),old=s.daily[k]||{pointsAwarded:0,bestTime:0,bestRank:99},score=base,delta=Math.max(0,score-(old.pointsAwarded||0));old.pointsAwarded=Math.max(old.pointsAwarded||0,score);old.bestRank=Math.min(old.bestRank||99,rank);if(!old.bestTime||totalTime<old.bestTime)old.bestTime=totalTime;s.daily[k]=old;const gain=awardXp(delta),marcas=globalThis.economyAwardSeasonMarks?economyAwardSeasonMarks('daily',delta):0;saveCareer();return{type:'daily',score,delta,gain,marcas};}
 if(raceContext.mode==='seasonGauntlet'){const g=s.gauntlet,w=weeklyEntry();g.score+=base;if(g.stage<2){g.stage++;saveCareer();return{type:'gauntlet',stage:g.stage,complete:false,score:g.score};}g.active=false;const score=g.score,delta=Math.max(0,score-(w.pointsAwarded||0));w.bestScore=Math.max(w.bestScore||0,score);w.pointsAwarded=Math.max(w.pointsAwarded||0,score);if(!w.bestTime||totalTime<w.bestTime)w.bestTime=totalTime;const gain=awardXp(delta),marcas=globalThis.economyAwardSeasonMarks?economyAwardSeasonMarks('weekly',delta):0;saveCareer();return{type:'gauntlet',stage:3,complete:true,score,delta,gain,marcas};}return null;};
globalThis.seasonAfterResult=function seasonAfterResult(){if(raceContext.mode==='seasonGauntlet'&&career.season.gauntlet.active){seasonStartGauntlet();return;}openSeason();};
globalThis.renderSeason=function renderSeason(){const d=ensureSeason(),dc=getCircuitDefinition(d.dailyLevel),w=career.season.weekly[d.weekKey]||{};document.getElementById('seasonTitle').textContent=`TEMPORADA HORIZONTE · ${d.key}`;document.getElementById('seasonDay').textContent=`DIA ${d.day+1}/28 · ${d.daysLeft} DIAS RESTANTES`;document.getElementById('seasonModifier').innerHTML=`<b>${d.modifier.name}</b><span>${d.modifier.desc}</span>`;document.getElementById('seasonDaily').innerHTML=`<b>DESTAQUE DE HOJE · FASE ${String(d.dailyLevel).padStart(3,'0')}</b><span>${dc?.name||'CIRCUITO HORIZONTE'} · melhor ${career.season.daily[dailyKey()]?.bestTime?formatTime(career.season.daily[dailyKey()].bestTime):'--:--.-'}</span>`;document.getElementById('seasonWeekly').innerHTML=`<b>GAUNTLET W${d.week+1} · ${d.weeklyLevels.map(x=>String(x).padStart(3,'0')).join(' → ')}</b><span>melhor score ${w.bestScore||0} · 3 provas / 1 volta</span>`;renderPass();renderBoard(d);document.getElementById('seasonGauntletAction').textContent=career.season.gauntlet.active&&career.season.gauntlet.key===d.weekKey?`CONTINUAR GAUNTLET ${career.season.gauntlet.stage+1}/3`:'⚔ INICIAR GAUNTLET';};
globalThis.openSeason=function openSeason(){gameMode='seasonmenu';renderSeason();showMenu('season');};
function bind(){document.getElementById('btnSeasonDaily')?.addEventListener('click',seasonStartDaily);document.getElementById('btnSeasonGauntlet')?.addEventListener('click',seasonStartGauntlet);document.getElementById('btnSeasonBack')?.addEventListener('click',()=>openModes());}
bind();ensureSeason();
