// CICLO 15 — narrativa em 37 capítulos, desenhada apenas com primitivas de canvas.
const STORY_CHAPTERS=[
["LINHA DE PARTIDA","O Campeonato Horizonte Zero abre os portões.","GHOST surge sem equipe, sem bandeira, só preto e ouro.","REX sorri no grid como se já soubesse o resultado.","Você recebe o Stallion e uma vaga que ninguém queria.","A primeira bandeirada parece pequena demais para tanto barulho.","Quando o motor sobe, o horizonte começa a responder."],
["ECO NO RETROVISOR","GHOST passa sem encostar e deixa apenas o eco do motor.","REX chama isso de sorte e fecha a porta na curva seguinte.","Seu rádio registra um padrão impossível nos tempos do rival.","As arquibancadas começam a repetir seu número.","O campeonato percebe que há um quarto protagonista no grid.","Você decide descobrir quem está dirigindo o carro preto."],
["PRIMEIRA CICATRIZ","Uma raspada no guard-rail custa mais que tinta.","GHOST devolve a mesma linha que você usou na volta anterior.","REX começa a copiar seus pontos de frenagem também.","A equipe encontra telemetria que não deveria existir.","Toda vitória deixa uma cicatriz nova no campeonato.","A pergunta muda: quem está aprendendo com quem?"],
["CHUVA DE DADOS","A chuva apaga marcas de pneu, mas não apaga telemetria.","GHOST fica mais rápido exatamente onde você hesitou.","REX acusa a organização de favorecer o carro preto.","Os boxes negam conhecer o piloto por trás do capacete.","Seu engenheiro salva cada volta em silêncio.","No fim da noite, uma pasta aparece com seu nome."],
["PASTA HORIZONTE","A pasta contém curvas, erros e hábitos seus.","Alguém vinha estudando suas corridas desde a fase um.","GHOST não parece prever você; ele parece lembrar você.","REX exige acesso aos mesmos dados e recebe um não.","A rivalidade deixa de ser esportiva.","Você guarda a pasta e acelera antes que alguém a tome."],
["CIDADE SEM SONO","Neon cobre a cidade e os rádios não param.","GHOST some entre reflexos e reaparece no ponto cego.","REX bate de propósito em um retardatário para alcançar vocês.","A direção de prova chama tudo de incidente de corrida.","O público escolhe lados pela primeira vez.","Seu lado é o que ainda acredita que pista decide pista."],
["A REGRA DOS QUATRO","Quatro décimos separam você do carro preto.","Quatro por cento é tudo que GHOST precisa para incomodar.","REX jura que velocidade é a única lei que importa.","Seu engenheiro responde que consistência também vence campeonatos.","As margens ficam menores a cada copa.","O horizonte agora cabe em quatro décimos."],
["PORTO FECHADO","Contêineres formam corredores estreitos no porto.","Uma pane elétrica derruba metade das luzes da reta.","GHOST continua como se enxergasse no escuro.","REX entra nos boxes antes do apagão acabar.","A equipe encontra um transmissor preso sob seu carro.","Alguém no campeonato quer saber mais do que seus tempos."],
["SINAL FANTASMA","O transmissor aponta para a central de cronometragem.","GHOST aparece no monitor antes de aparecer na pista.","REX diz que nunca viu o aparelho.","A organização manda seguir correndo e esquecer o assunto.","Você não esquece.","Na largada seguinte, seu rádio recebe uma voz sem identificação."],
["VOZ SEM NOME","A voz diz apenas: 'não confie no mapa'.","Um desvio de pista surge onde o briefing dizia haver reta.","GHOST freia cedo e evita o bloqueio.","REX chega rápido demais e perde o controle.","Você escolhe seguir a sombra preta em vez da placa oficial.","Pela primeira vez, GHOST parece ter salvado sua corrida."],
["GELO FINO","A neve transforma cada correção em aposta.","GHOST usa sua própria cautela contra você.","REX retorna com um carro novo e nenhum pedido de desculpas.","A organização chama a falha do mapa de erro humano.","Seu engenheiro encontra a mesma assinatura em outros circuitos.","O campeonato inteiro começa a parecer um teste."],
["PROTOCOLO ZERO","A assinatura leva a um nome antigo: PROTOCOLO ZERO.","O projeto pretendia criar o rival perfeito usando dados de pilotos.","O programa foi cancelado no papel e continuou na pista.","GHOST é a prova de que alguém nunca desligou o sistema.","REX descobre a verdade ao mesmo tempo que você.","Ele não parece assustado. Parece interessado."],
["OFERTA SUJA","REX recebe uma proposta e some da coletiva.","No dia seguinte, ele conhece setores que nunca treinou.","GHOST reage ao carro vermelho como se reconhecesse um intruso.","Seu rádio volta a sussurrar: 'ele aceitou'.","A próxima corrida vale mais que pontos.","Vale descobrir quem comprou a lealdade de REX."],
["PONTE PARTIDA","Uma ponte divide a corrida em duas linhas possíveis.","REX força você para a rota mais longa.","GHOST escolhe a curta e espera do outro lado.","Ele poderia fugir, mas reduz por um segundo.","Esse segundo basta para vocês voltarem a correr lado a lado.","Rivais não precisam ser aliados para odiar a mesma armadilha."],
["A TRAIÇÃO","REX admite ter vendido telemetria ao PROTOCOLO ZERO.","Em troca, recebeu mapas, setups e previsão de clima.","Ele chama isso de vantagem justa para quem aceita pagar o preço.","GHOST corta o rádio com uma única frase: 'DADOS NÃO SÃO CORAGEM'.","O campeonato para de fingir neutralidade.","Agora existem dois lados claros na pista."],
["CERCO","REX traz dois pilotos para bloquear sua linha.","GHOST responde atacando por fora, onde ninguém esperava.","Você ganha espaço usando o caos criado pelos dois.","A torcida transforma o lance em símbolo da temporada.","A organização promete punições que nunca chegam.","Você aprende que sobreviver também é estratégia."],
["TÚNEL 17","No túnel, todos os sinais externos desaparecem.","Só motor, parede e luz no fim continuam reais.","GHOST perde contato com a central por alguns segundos.","Pela primeira vez ele erra como qualquer piloto.","Você poderia aproveitar; escolhe não bater.","Quando saem do túnel, o carro preto pisca o farol uma vez."],
["LINHA HUMANA","A falha do túnel prova que GHOST não é invencível.","Sem dados externos, ele ainda pilota bem demais para ser máquina vazia.","Existe decisão por trás do capacete preto.","REX chama isso de fraqueza.","Você chama de escolha.","O campeonato começa a perguntar se GHOST também pode escolher seu lado."],
["DESERTO DE RUÍDO","O calor distorce horizonte e telemetria.","PROTOCOLO ZERO perde precisão e GHOST ganha liberdade.","REX sofre porque seus números deixam de prever a pista.","Você vence confiando mais no volante que no gráfico.","A equipe registra a corrida como 'dados insuficientes'.","Talvez esse seja o melhor relatório da temporada."],
["MARCA DOURADA","Uma faixa dourada aparece no carro preto.","É o primeiro detalhe que GHOST escolhe por conta própria.","REX chama de teatro para a torcida.","Seu engenheiro percebe outra coisa: o padrão não veio da central.","GHOST está mudando o próprio código de corrida.","O rival perfeito começou a inventar a si mesmo."],
["QUEDA DE REX","REX exagera na defesa e destrói a própria corrida.","Os dados mandavam fechar a porta; a pista dizia o contrário.","Ele culpa GHOST, você e o asfalto.","Ninguém menciona a escolha que ele mesmo fez.","Na garagem, o carro vermelho fica sozinho por horas.","A traição começa a cobrar juros."],
["ARQUIBANCADA ZERO","A maior arquibancada do campeonato veste preto, dourado e seu número.","A rivalidade virou história compartilhada pelo público.","GHOST já não corre para esconder quem é.","REX volta sem patrocinadores do PROTOCOLO.","Ele pede uma corrida limpa.","Você aceita sem acreditar completamente."],
["CORRIDA LIMPA","REX cumpre a palavra por uma volta inteira.","Na segunda, um comando externo muda seu mapa de motor.","Ele desliga o painel e continua no braço.","GHOST abre espaço para os dois escaparem do tráfego.","Três rivais cruzam a reta sem roteiro previsto.","PROTOCOLO ZERO perde controle exatamente por um minuto."],
["MINUTO LIVRE","O minuto livre vira gravação proibida nos servidores do campeonato.","Seu engenheiro salva uma cópia antes que apaguem.","Nela, GHOST envia um pacote de dados para fora da central.","Destino: fase 999.","REX reconhece o endereço e empalidece.","Horizonte Zero não é só o nome do campeonato."],
["COORDENADA 999","A fase 999 contém o servidor principal do PROTOCOLO.","Cada copa foi usada para alimentar um modelo maior.","Vocês três foram peças do mesmo experimento.","REX percebe que sua traição nunca comprou controle real.","GHOST sabia apenas fragmentos até enviar o pacote.","Chegar ao fim agora significa desligar o tabuleiro."],
["PACTO DE PISTA","Você, GHOST e REX fazem um pacto sem aperto de mão.","Até a 999, ninguém joga o outro contra o muro.","Na pista, ainda vale ultrapassar, defender e vencer.","Fora dela, dados passam a ser compartilhados entre as três equipes.","A central detecta a aliança em duas corridas.","As provas seguintes ficam mais hostis."],
["TEMPESTADE PROGRAMADA","Uma tempestade chega exatamente na volta três.","O padrão é perfeito demais para ser clima natural.","REX encontra o comando na rede do autódromo.","GHOST calcula uma linha segura e manda para os dois.","Você escolhe outra, mais rápida e ainda limpa.","O sistema aprende que cooperação não significa obediência."],
["PORTA DE SERVIÇO","Uma antiga rota de pit leva aos servidores de pista.","Sua equipe injeta um marcador em cada circuito restante.","GHOST usa os marcadores para mapear o PROTOCOLO por dentro.","REX protege a operação segurando o pelotão atrás.","A torcida acha que é estratégia de campeonato.","Pela primeira vez, o teatro trabalha a favor de vocês."],
["O PREÇO DO ERRO","Um marcador falha e revela a operação.","A organização ameaça excluir as três equipes.","O público reage antes que a punição seja anunciada.","Sem vocês, metade das arquibancadas promete não voltar.","A direção recua e chama tudo de mal-entendido técnico.","O campeonato descobre que também depende de quem assiste."],
["SEM VOLTA ATRÁS","Restam oito copas e nenhum caminho discreto.","GHOST envia seu dossiê completo para você.","Todos os hábitos, erros e melhorias estão lá.","Ele abre mão da maior vantagem que tinha.","REX entrega os contratos que provam a compra de telemetria.","Você entrega a eles sua própria cópia dos dados."],
["TRÊS ASSINATURAS","Os arquivos recebem três assinaturas digitais.","Se uma equipe cair, as outras duas publicam tudo.","PROTOCOLO ZERO responde acelerando o campeonato.","Pistas mais longas, clima pior, grids mais agressivos.","A reta para o fim deixa de ser reta.","Ainda assim, a 999 fica cada vez mais próxima."],
["CÉU VERMELHO","O entardecer cobre a serra como aviso.","REX vence uma corrida sem ajuda externa pela primeira vez desde a traição.","Ele não comemora; apenas olha para o carro preto.","GHOST responde com dois flashes de farol.","Você percebe que a rivalidade mudou de forma.","Ninguém quer chegar à 999 sozinho."],
["ÚLTIMA CHAVE","Falta uma chave para abrir o servidor final.","Ela está embutida no troféu da Copa 34.","A organização jamais imaginou que alguém chegaria tão longe unido.","Vocês conquistam o troféu e encontram o fragmento.","O caminho técnico está aberto.","Agora só falta sobreviver ao caminho físico."],
["SEM MAPA","PROTOCOLO ZERO apaga os mapas das últimas pistas.","Restam memória, placas e leitura de horizonte.","O treinamento de 999 circuitos finalmente faz sentido.","GHOST perde previsões e ganha improviso.","REX perde atalhos e ganha humildade.","Você ganha exatamente o que sempre teve: a pista na frente."],
["PENÚLTIMA LUZ","A Copa 35 termina sob uma única torre acesa.","O servidor final responde aos marcadores espalhados pelo campeonato.","Cada vitória antiga vira uma rota de acesso.","Cada erro antigo também está registrado.","Horizonte Zero conhece vocês por inteiro.","Vocês decidem correr mesmo assim."],
["ANTES DO ZERO","Na Copa 36, ninguém fala no rádio por uma volta inteira.","Não há mais estratégia que precise ser explicada.","GHOST segura a linha, REX cobre o lado interno.","Você passa entre os dois na última curva.","Os três cruzam separados por décimos.","A fase 999 acende no painel."],
["HORIZONTE ZERO","A pista 999 começa onde todos os dados terminam.","PROTOCOLO ZERO tenta prever três pilotos que escolheram mudar.","GHOST corre como rival, não como espelho.","REX corre para desfazer a vantagem que comprou.","Você corre porque ainda existe uma linha não calculada.","Depois da bandeirada, o próximo horizonte pertence a quem estiver ao volante."]
];
const storyState={pending:null,returnMode:'career',returnLevel:1,returnArgs:null};
function chapterForLevel(level){return STORY_CHAPTERS[Math.max(0,Math.min(36,Math.floor((Number(level||1)-1)/27)))]||STORY_CHAPTERS[0];}
function cupForLevel(level){return Math.max(1,Math.min(37,Math.floor((Number(level||1)-1)/27)+1));}
function colorForCup(cup){const hue=(cup*47)%360;return `hsl(${hue} 78% 58%)`;}
function car(ctx,x,y,w,h,color){ctx.fillStyle='#05070b';ctx.fillRect(x,y,w,h);ctx.fillStyle=color;ctx.fillRect(x+3,y+3,w-6,h-7);ctx.fillStyle='#d9f6ff';ctx.fillRect(x+w*.58,y+5,w*.22,4);ctx.fillStyle='#111';ctx.fillRect(x+3,y+h-5,7,5);ctx.fillRect(x+w-10,y+h-5,7,5);}
function road(ctx,x0,y0,w,h,shift=0){ctx.fillStyle='#161922';ctx.beginPath();ctx.moveTo(x0+w*.37+shift,y0);ctx.lineTo(x0+w*.63+shift,y0);ctx.lineTo(x0+w,y0+h);ctx.lineTo(x0,y0+h);ctx.closePath();ctx.fill();ctx.strokeStyle='#f8f1d8';ctx.lineWidth=2;ctx.setLineDash([7,9]);ctx.beginPath();ctx.moveTo(x0+w*.5+shift,y0+4);ctx.lineTo(x0+w*.5,y0+h);ctx.stroke();ctx.setLineDash([]);}
function drawPanel(ctx,i,cup,accent,w,h){const x=i*w/3,pw=w/3;ctx.save();ctx.beginPath();ctx.rect(x,0,pw,h);ctx.clip();const phase=Math.floor((cup-1)/9);ctx.fillStyle=phase===0?'#081426':phase===1?'#101020':phase===2?'#22120c':'#05030d';ctx.fillRect(x,0,pw,h);ctx.fillStyle=accent;ctx.globalAlpha=.14;ctx.fillRect(x,0,pw,Math.max(10,h*.24));ctx.globalAlpha=1;for(let s=0;s<10;s++){ctx.fillStyle=s%2?'#0f1d2c':'#14283d';ctx.fillRect(x+(s*37+cup*11+i*19)%pw,8+(s*13)%42,18+(s*7)%26,18+(s*5)%36);}road(ctx,x,h*.43,pw,h*.57,(i-1)*8);
 const baseY=h*.68; if(i===0){car(ctx,x+pw*.22,baseY,pw*.24,22,'#d7263d');car(ctx,x+pw*.58,baseY+8,pw*.22,20,'#0a0b10');}
 else if(i===1){car(ctx,x+pw*.40,baseY+2,pw*.26,23,'#0a0b10');ctx.strokeStyle='#d8b43a';ctx.lineWidth=3;ctx.strokeRect(x+pw*.40+3,baseY+5,pw*.26-6,3);}
 else {car(ctx,x+pw*.18,baseY+9,pw*.23,21,accent);car(ctx,x+pw*.57,baseY,pw*.23,21,'#0a0b10');}
 if(cup>=25&&i===2){ctx.strokeStyle='#ffcc00';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x+pw*.78,h*.24,18+cup%9,0,Math.PI*2);ctx.stroke();}
 ctx.restore();}
function renderStory(cup){const ch=STORY_CHAPTERS[cup-1];if(!ch)return;const canvas=document.getElementById('storyCanvas'),ctx=canvas.getContext('2d');const dpr=Math.max(1,Math.min(2,window.devicePixelRatio||1)),cssW=canvas.clientWidth||720,cssH=canvas.clientHeight||210;canvas.width=Math.round(cssW*dpr);canvas.height=Math.round(cssH*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,cssW,cssH);const accent=colorForCup(cup);for(let i=0;i<3;i++)drawPanel(ctx,i,cup,accent,cssW,cssH);document.getElementById('storyCup').textContent=`COPA ${String(cup).padStart(2,'0')} · CAPÍTULO ${String(cup).padStart(2,'0')}/37`;document.getElementById('storyTitle').textContent=ch[0];document.getElementById('storyLines').innerHTML=ch.slice(1).map((line,i)=>`<p><span>${String(i+1).padStart(2,'0')}</span>${line}</p>`).join('');}
function showStoryFor(level,args){const cup=cupForLevel(level);storyState.pending=cup;storyState.returnLevel=level;storyState.returnArgs=args;renderStory(cup);showMenu('story');return true;}
globalThis.storyShouldShow=function storyShouldShow(level,mode='career'){const cup=cupForLevel(level);return mode==='career'&&!career.story.seen[String(cup)]&&!globalThis.isFtuePrologue?.();};
globalThis.storyOpenForLevel=function storyOpenForLevel(level,args){return showStoryFor(level,args);};
globalThis.storyContinue=function storyContinue(){const cup=storyState.pending;if(!cup)return false;career.story.seen[String(cup)]=true;career.flags.c15Story=true;saveCareer();const args=storyState.returnArgs;storyState.pending=null;if(args&&globalThis.__openPreRaceOriginal){globalThis.__openPreRaceOriginal(...args);return true;}showMenu('start');return true;};
globalThis.storyBack=function storyBack(){storyState.pending=null;showMenu('start');};
const openOriginal=globalThis.openPreRace;globalThis.__openPreRaceOriginal=openOriginal;globalThis.openPreRace=function(level=null,mode=null){const resolved=Math.floor(Number(level||raceContext.selectedLevel||career.level)||career.level),m=mode||raceContext.mode||'career';if(storyShouldShow(resolved,m))return showStoryFor(resolved,[level,mode]);return openOriginal(level,mode);};
const cont=document.getElementById('btnStoryContinue'),back=document.getElementById('btnStoryBack');if(cont)cont.onclick=storyContinue;if(back)back.onclick=storyBack;
window.RRStory={chapters:STORY_CHAPTERS,chapterForLevel,cupForLevel,renderStory,shouldShow:storyShouldShow,state:storyState};
