// CICLO 13 — Treinador pós-corrida: traço da melhor volta, perdas por setor e UMA dica acionável.
const TRACE_BINS=30;let session=null,lastResult=null;
function emptyLap(){return{trace:new Array(TRACE_BINS).fill(null),cross:[null,null],offroad:[0,0,0],crashes:[0,0,0],nitro:[0,0,0],lastOffroad:raceOffroadSeconds||0,lastCrashes:raceCrashes||0};}
function refFor(level){const r=career.coach&&career.coach.traces&&career.coach.traces[level];return r&&Array.isArray(r.trace)&&Array.isArray(r.sectors)?r:null;}
function safeTrace(a,time){const out=new Array(TRACE_BINS);let last=0;for(let i=0;i<TRACE_BINS;i++){const v=Number(a&&a[i]);if(Number.isFinite(v)&&v>=last)last=v;else if(i===TRACE_BINS-1)last=time;out[i]=Math.round(last*100)/100;}out[TRACE_BINS-1]=Math.round(time*100)/100;return out;}
function sectorLabel(i){return'S'+(i+1);}
function makeTip(cur,ref){let worst=0,loss=-Infinity;if(ref)for(let i=0;i<3;i++){const d=cur.sectors[i]-ref.sectors[i];if(d>loss){loss=d;worst=i;}}else{const scores=cur.offroad.map((v,i)=>v*1.8+cur.crashes[i]*2.5);worst=scores.indexOf(Math.max(...scores));loss=0;}
  if(cur.crashes[worst]>0)return`${sectorLabel(worst)}: freie um pouco antes e priorize a saída — ${cur.crashes[worst]} batida${cur.crashes[worst]>1?'s':''} matou${cur.crashes[worst]>1?'ram':''} o setor.`;
  if(cur.offroad[worst]>.35)return`${sectorLabel(worst)}: entre 5% mais cedo e mantenha o carro no asfalto; foram ${cur.offroad[worst].toFixed(1)}s fora da pista.`;
  if(cur.nitro[worst]<.18&&(!ref||loss>.20))return`${sectorLabel(worst)}: guarde um pulso curto de nitro para a saída e carregue velocidade até o próximo setor.`;
  if(ref&&loss>.08)return`${sectorLabel(worst)}: sua linha está limpa; carregue mais velocidade na saída para recuperar ${loss.toFixed(2)}s.`;
  return`Repita a volta: os três setores estão consistentes. Agora procure ganhar décimos sem aumentar risco.`;
}
function finishLap(lapTime){if(!session||lapTime<=5)return;const l=session.lap,c1=Number(l.cross[0])||lapTime/3,c2=Number(l.cross[1])||lapTime*2/3;const cur={time:+lapTime.toFixed(3),trace:safeTrace(l.trace,lapTime),sectors:[+c1.toFixed(3),+(c2-c1).toFixed(3),+(lapTime-c2).toFixed(3)],offroad:l.offroad.map(v=>+v.toFixed(3)),crashes:[...l.crashes],nitro:l.nitro.map(v=>+v.toFixed(3))};if(!session.best||cur.time<session.best.time)session.best=cur;session.lap=emptyLap();}
function persistBest(cur){if(!cur)return;career.coach=career.coach||{traces:{},last:null};career.coach.traces=career.coach.traces||{};const old=refFor(raceLevel);if(!old||cur.time<Number(old.time||Infinity))career.coach.traces[raceLevel]={time:cur.time,sectors:[...cur.sectors],trace:[...cur.trace]};}
function buildResult(){if(!session||!session.best)return null;const cur=session.best,ref=session.reference;const losses=ref?cur.sectors.map((v,i)=>+(v-ref.sectors[i]).toFixed(3)):[null,null,null];const result={level:raceLevel,time:cur.time,reference:ref?{time:Number(ref.time),sectors:[...ref.sectors],trace:[...ref.trace]}:null,current:cur,losses,tip:makeTip(cur,ref),newBest:!ref||cur.time<Number(ref.time)};lastResult=result;career.coach.last={level:result.level,time:result.time,losses:result.losses,tip:result.tip,newBest:result.newBest};career.flags.c13Coach=true;persistBest(cur);return result;}
function drawTrace(result){const c=document.getElementById('coachTraceCanvas');if(!c||!result)return;const g=c.getContext('2d'),w=c.width,h=c.height,pad=18;g.clearRect(0,0,w,h);g.fillStyle='#04070d';g.fillRect(0,0,w,h);g.strokeStyle='rgba(255,255,255,.10)';g.lineWidth=1;for(let i=0;i<=3;i++){const x=pad+(w-pad*2)*i/3;g.beginPath();g.moveTo(x,pad);g.lineTo(x,h-pad);g.stroke();}const traces=[{a:result.reference&&result.reference.trace,c:'#ffcc00'},{a:result.current.trace,c:'#38d5ff'}].filter(x=>x.a);let max=0;for(const t of traces)for(const v of t.a)max=Math.max(max,Number(v)||0);max=Math.max(max,1);for(const t of traces){g.strokeStyle=t.c;g.lineWidth=3;g.beginPath();t.a.forEach((v,i)=>{const x=pad+(w-pad*2)*i/(TRACE_BINS-1),y=h-pad-(h-pad*2)*(Number(v)||0)/max;if(i===0)g.moveTo(x,y);else g.lineTo(x,y);});g.stroke();}g.fillStyle='#ffcc00';g.font='900 10px monospace';g.fillText('MELHOR',pad,12);g.fillStyle='#38d5ff';g.fillText('VOCÊ',pad+60,12);}
globalThis.coachRaceStart=function coachRaceStart(){if(raceContext.mode==='license'){session=null;return;}session={reference:refFor(raceLevel)?structuredClone(refFor(raceLevel)):null,best:null,lap:emptyLap()};lastResult=null;};
globalThis.coachTick=function coachTick(dt){if(!session||!raceStarted||finished||gameOver||trackZLength<=0)return;const frac=posMod(playerProgress+playerZ,trackZLength)/trackZLength,l=session.lap,bin=Math.max(0,Math.min(TRACE_BINS-1,Math.floor(frac*TRACE_BINS))),sec=Math.max(0,Math.min(2,Math.floor(frac*3)));if(l.trace[bin]==null)l.trace[bin]=currentLapTime;if(l.cross[0]==null&&frac>=1/3)l.cross[0]=currentLapTime;if(l.cross[1]==null&&frac>=2/3)l.cross[1]=currentLapTime;const off=Math.max(0,raceOffroadSeconds-l.lastOffroad);if(off>0)l.offroad[sec]+=off;l.lastOffroad=raceOffroadSeconds;const cr=Math.max(0,raceCrashes-l.lastCrashes);if(cr>0)l.crashes[sec]+=cr;l.lastCrashes=raceCrashes;if(nitroWasActive)l.nitro[sec]+=dt;};
globalThis.coachLapComplete=function coachLapComplete(lapTime){finishLap(lapTime);};
globalThis.coachRaceFinish=function coachRaceFinish(){return buildResult();};
globalThis.coachRenderResult=function coachRenderResult(){const box=document.getElementById('coachPanel');if(!box)return;const r=lastResult;box.classList.toggle('hidden',!r);if(!r)return;document.getElementById('coachTitle').textContent=r.newBest?(r.reference?'NOVO RECORDE · TREINADOR':'REFERÊNCIA GRAVADA · TREINADOR'):'TREINADOR · CONTRA SUA MELHOR';for(let i=0;i<3;i++){const el=document.getElementById('coachSector'+(i+1)),d=r.losses[i];el.innerHTML=`<b>S${i+1}</b><span>${d==null?'BASE':(d<=0?'−':'+')+Math.abs(d).toFixed(2)+'s'}</span>`;el.className='coach-sector '+(d==null?'base':d<=0?'gain':'loss');}document.getElementById('coachTip').textContent=r.tip;drawTrace(r);};
globalThis.coachSnapshot=function coachSnapshot(){return{session:session?{hasReference:!!session.reference,best:session.best}:null,last:lastResult,stored:refFor(raceLevel)};};
