// ES module nativo — bindings compartilhados explícitos via globalThis durante a migração arquitetural.
globalThis.showMenu = function showMenu(name) {
    document.querySelectorAll('.menu-overlay').forEach(el => el.classList.add('hidden'));
    if (name) { document.getElementById('menu-' + name).classList.remove('hidden'); wrapper.classList.add('menu-open'); }
    else wrapper.classList.remove('menu-open'); applyUiSettings();
    if (name === 'start' || name === 'help' || name==='rift' || name==='season' || name==='licenses' || name==='paint' || name === 'stats' || name === 'settings' || name==='cups' || name==='tracks' || name==='modes' || name==='trophies' || name==='almanac' || name==='ghost' || name==='shadow' || name==='story' || name==='highlight' || name==='economy' || name==='metrics' || name==='credits') {
        if (window.RetroRacerMusic999Bridge) { try { window.RetroRacerMusic999Bridge.stop(); } catch (e) {} }
        startMusic();
    }
}
globalThis.updateStartBadges = function updateStartBadges() { career.stats.cups=Math.max(career.stats.cups||0,Math.max(0,Math.ceil(career.level/27)-1)); document.getElementById('startLevelTag').innerText = 'FASE ' + career.level; document.getElementById('startCarTag').innerText = currentCar().name.toUpperCase(); document.getElementById('startMoneyTag').innerText = money(career.money); const ft=document.getElementById('startFichasTag');if(ft)ft.innerText='FICHAS '+Math.floor(career.fichas||0).toLocaleString('pt-BR');const mt=document.getElementById('startMarcasTag');if(mt)mt.innerText='MARCAS '+Math.floor(career.marcas||0).toLocaleString('pt-BR'); updateHud(lastRacePosition || 1, cars.length + 1); }
globalThis.openPreRace = function openPreRace(level=null,mode=null) {
    garageReturn='prerace'; if(mode)raceContext.mode=mode; raceLevel=Math.floor(clampNumber(level||raceContext.selectedLevel||career.level,1,999,career.level)); raceContext.selectedLevel=raceLevel; raceContext.replay=raceContext.mode==='career'&&raceLevel!==career.level; totalLaps=['shadow','rift','license'].includes(raceContext.mode)?1:(raceContext.mode==='endurance'?15:(raceContext.laps||5)); const circuit=getCircuitDefinition(raceLevel); buildTrack();
    document.getElementById('preRaceTitle').innerText=(circuit?circuit.name:biomeLabel(raceBiome())).toUpperCase(); document.getElementById('preRaceSubtitle').innerText=circuitSubtitle(circuit)+(raceContext.replay?' · REPLAY: 55% DO PRÊMIO':''); document.getElementById('preCar').innerText=currentCar().name;document.getElementById('preLaps').innerText=String(totalLaps);const lapRow=document.getElementById('preLapsRow'),lapSel=document.getElementById('preLapsSelect');lapRow.classList.toggle('hidden',raceContext.mode!=='quick');lapSel.value=String(raceContext.laps||5);const isLicense=raceContext.mode==='license',ld=isLicense&&globalThis.licenseCurrentDef?licenseCurrentDef():null;document.getElementById('preGoldLabel').innerText=isLicense?'Tempo limite':'Tempo Ouro';document.getElementById('preGold').innerText=isLicense&&ld?ld.duration.toFixed(1)+'s':formatTime(targetGoldTime);document.getElementById('prePrizePanel').classList.toggle('hidden',isLicense);document.getElementById('preInsuranceRow').classList.toggle('hidden',isLicense);document.getElementById('preSponsorRow').classList.toggle('hidden',isLicense); const pr=racePrizes(raceLevel,raceContext.replay);if(raceContext.mode==='timeTrial'){pr[0]=Math.round(pr[0]*.20);pr[1]=0;pr[2]=0;}if(['shadow','license'].includes(raceContext.mode)){pr[0]=pr[1]=pr[2]=0;}document.getElementById('prePrize1').innerText=money(pr[0]);document.getElementById('prePrize2').innerText=money(pr[1]);document.getElementById('prePrize3').innerText=money(pr[2]);document.getElementById('preMode').innerText=raceContext.mode==='seasonDaily'?'TEMPORADA · DIÁRIA':raceContext.mode==='seasonGauntlet'?'TEMPORADA · GAUNTLET':raceContext.mode==='license'?'LICENÇA':raceContext.mode.toUpperCase();document.getElementById('preRecord').innerText=formatTime(Number(career.records[raceLevel]||Infinity));document.getElementById('preTireSelect').value=career.settings.tire||'MISTO';document.getElementById('preInsurance').checked=!!raceContext.insurance;document.getElementById('btnPreGarage').classList.toggle('hidden',['rift','license'].includes(raceContext.mode));document.getElementById('preInsurance').disabled=['rift','license'].includes(raceContext.mode);if(raceContext.mode==='rift')document.getElementById('preRaceSubtitle').innerText+=' · FENDA: BANCO EM RISCO';if(raceContext.mode==='license'&&globalThis.licensePreRaceText)document.getElementById('preRaceSubtitle').innerText=licensePreRaceText();drawRibbon(document.getElementById('preRacePreview'),circuit);gameMode='prerace';showMenu('prerace');
}
globalThis.startRace = function startRace() {
                if(window.RRCore&&window.RRCore.rng) window.RRCore.rng.beginRace(raceContext.mode==='shadow'&&raceContext.shadowSeed?raceContext.shadowSeed:`${raceContext.selectedLevel||career.level}|${raceContext.mode}|${raceContext.dailySeed||0}`);
                if(window.RRCore&&window.RRCore.replay) window.RRCore.replay.start({level:raceContext.selectedLevel||career.level,mode:raceContext.mode,seed:window.RRCore.rng.seed});
    resumeAudio(); raceLevel=Math.floor(clampNumber(raceContext.selectedLevel||career.level,1,999,career.level));if(globalThis.telemetryEvent)telemetryEvent('race_start',{mode:raceContext.mode,level:raceLevel,car:career.selectedCar}); totalLaps=['shadow','rift','license'].includes(raceContext.mode)?1:(raceContext.mode==='endurance'?15:(raceContext.laps||5)); raceInsurance=!!raceContext.insurance; raceDamageStart=Number(career.carDamage[currentCar().id]||0); gameMode='race';gamePaused=false;finished=false;gameOver=false;raceAwarded=false;finalRankingLocked=false;buildTrack();resetRaceStateOnly();initCars();if(globalThis.coachRaceStart)coachRaceStart();if(globalThis.licenseRaceStart)licenseRaceStart();if(globalThis.riftApplyRaceStart)riftApplyRaceStart(); if(globalThis.shadowRaceStart)shadowRaceStart(); if(globalThis.highlightRaceStart)highlightRaceStart(); if(raceContext.mode==='timeTrial'){cars=[];totalRacersDisplay.innerText='1';} if(raceContext.mode==='shadow'){cars=[];shadowGhosts=globalThis.shadowBuildRaceGhosts?shadowBuildRaceGhosts(trackZLength):[];totalRacersDisplay.innerText=String(shadowGhosts.length+1);} if(raceContext.mode==='boss'){cars=cars.filter(c=>c.name==='GHOST');if(cars.length){cars[0].progress=playerZ+900;cars[0].baseSpeed*=1.08;}totalRacersDisplay.innerText=String(cars.length+1);} const savedGhost=career.ghosts[raceLevel]||null; ghostReplay=savedGhost&&savedGhost.inputReplay&&window.RRCore&&window.RRCore.replay?window.RRCore.replay.toGhostSamples(savedGhost.inputReplay,trackZLength*totalLaps,Number(savedGhost.time)||0):(savedGhost&&savedGhost.samples)||[]; runtimeWeather=raceContext.weatherOverride||null;dynamicWeatherArmed=hashNumber(raceLevel*9.17)<.10&&!['rain','storm','snow'].includes((activeCircuit&&activeCircuit.weather)||''); countdownActive=true;countdownTimer=3.15;countdownText='3';goFlashTimer=0;showMenu(null);applyUiSettings();raceMessage='';raceMessageTimer=0;touchHint.classList.add('hidden');tutorialHintThisRace=!career.flags.touchHintSeen;if(tutorialHintThisRace){career.flags.touchHintSeen=true;saveCareer();}playSFX('beep');if(window.RRCore&&window.RRCore.assets)window.RRCore.assets.ensureMusicBank().then(()=>{if(window.RetroRacerMusic999Bridge)window.RetroRacerMusic999Bridge.playForLevel(raceLevel);}).catch(()=>{}); if([27,333,666,999].includes(raceLevel))radio(raceLevel===999?'HORIZONTE ZERO · FINAL':'EVENTO LENDÁRIO · '+raceLevel,2.3); if(raceContext.mode==='shadow'&&shadowGhosts.length)radio('SOMBRA DE '+shadowGhosts[0].alias+' NA PISTA',2.1); if(globalThis.isCopilotMode&&isCopilotMode())setRaceMessage('COPILOTO · ACELERAÇÃO AUTOMÁTICA','#38d5ff',1.8); if(globalThis.isLegendaryMode&&isLegendaryMode())radio('LENDÁRIO · SEM BORRACHA · GHOST +8%',2.0);
}
globalThis.resetRaceStateOnly = function resetRaceStateOnly() { playerProgress=0;position=0;speed=0;playerX=0;skyOffset=0;hillOffset=0;treeOffset=0;cityParallaxSpeed=0;cityFarOffset=0;cityMidOffset=0;cityNearOffset=0;cityDeckOffset=0;globalParallaxSpeed=0;globalSkyPx=0;globalMountainFarPx=0;globalMountainMidPx=0;globalGroundNearPx=0;raceStarted=false;currentLap=1;currentLapTime=0;totalRaceTime=0;particles=[];nitro=1;fuel=calcMods().fuelCapacity;draftTimer=0;draftBoost=0;raceMessage='';raceMessageTimer=0;cameraShake=0;playerCollisionCooldown=0;nitroFlamePulse=0;pitTimer=0;pitServiceProgress=0;pitServiceActive=false;pitServiceDone=false;pitRejectCooldown=0;nitroArmTimer=0;nitroWasRequested=false;nitroWasActive=false;cleanLapEligible=true;perfectStartWindow=0;perfectStartBoost=0;jumpStartQueued=false;jumpStartPenalty=0;impactFreeze=0;renderLookaheadX=0;countdownActive=false;countdownTimer=0;countdownText='';goFlashTimer=0;lastRacePosition=null;finalRanking=[];finalPlayerRank=1;finalTotalTime=0;finalBestLap=Infinity;racePits=0;raceCrashes=0;raceOffroadSeconds=0;ghostSampleTimer=0;ghostReplay=[];shadowGhosts=[];runtimeWeather=null;dynamicWeatherAnnounced=false;finishBannerTimer=0;photoFinishSlowmo=0;lastPitRadioLap=0;if(globalThis.resetJuiceEffects)resetJuiceEffects();if(globalThis.resetHaptics)resetHaptics();if(globalThis.resetAdaptiveAudio)resetAdaptiveAudio();if(globalThis.resetRiskCombo)resetRiskCombo();if(raceContext.mode!=='rift')document.body.classList.remove('rift-minimal-hud');if(globalThis.ghostLearningStart)ghostLearningStart();if(pitHud)pitHud.classList.remove('show');if(curveHud)curveHud.classList.remove('show');clearKeys();updateHud(cars.length+1,cars.length+1); }
globalThis.togglePause = function togglePause() { if (gameMode !== 'race') return; gamePaused = !gamePaused; if (gamePaused) { fadeAudioOut(); if (window.RetroRacerMusic999Bridge) window.RetroRacerMusic999Bridge.pause(); showMenu('pause'); } else { if (window.RetroRacerMusic999Bridge) window.RetroRacerMusic999Bridge.resume(); showMenu(null); } }
globalThis.openGarage = function openGarage(ret = 'start') { if(globalThis.telemetryEvent)telemetryEvent('garage_open',{car:career.selectedCar}); garageReturn = ret; garageCarView = career.selectedCar; gameMode = ret === 'pause' ? 'race' : 'garage'; renderGarage(); showMenu('garage'); }
globalThis.renderGarage = function renderGarage() {
    refreshCarUnlocks(); const car=CARS[garageCarView], unlocked=career.unlockedCars.includes(car.id), available=carAvailable(car); document.getElementById('garageCarName').innerText=car.name;document.getElementById('garageMoney').innerText=money(career.money);if(globalThis.renderRiskCosmetics)renderRiskCosmetics();document.getElementById('garageDamage').innerText=Math.round((career.carDamage[car.id]||0)*100)+'%';document.getElementById('garageProfile').innerText=car.profile;document.getElementById('garageUnlock').innerText=unlocked?'DESBLOQUEADO · '+car.quote:'CONDIÇÃO: '+carUnlockReason(car);
    const btn=document.getElementById('btnSelectBuyCar'); if(unlocked){btn.innerText=career.selectedCar===car.id?'SELECIONADO':'SELECIONAR';btn.disabled=career.selectedCar===car.id;}else{btn.innerText=available?(car.price?('COMPRAR '+money(car.price)):'DESBLOQUEAR'):'BLOQUEADO';btn.disabled=!available||(car.price>0&&career.money<car.price);}
    const repCost=Math.ceil((career.carDamage[car.id]||0)*2500);const repBtn=document.getElementById('btnRepairCar');repBtn.innerText=repCost>0?'REPARAR '+money(repCost):'SEM DANOS';repBtn.disabled=repCost<=0||career.money<repCost;
    const stats=[['SPEED',car.speed],['ACCEL',car.accel||car.speed],['GRIP',car.grip],['FUEL',2-car.fuel],['ARMOR',car.armor],['NITRO',car.nitro]];document.getElementById('garageStats').innerHTML=stats.map(x=>`<div class="stat-chip">${x[0]}<b>${Math.round(MathUtils.limit(x[1],.55,1.35)/1.35*99)}</b></div>`).join('');
    const skins=document.getElementById('garageSkins'),base=CAR_SKINS[car.id]||[car.color,car.stripe],sel=Number(career.selectedSkin[car.id]||0),chrome=!!career.skins.chromeUnlocked,liv=career.liveries&&career.liveries[car.id],custom=!!(liv&&liv.active!==false);skins.innerHTML=[0,1,2].map(i=>{const locked=i===2&&!chrome;const title=i===0?'Stock':i===1?'Midnight':'Chrome · 3 ouros seguidos';return `<button class="skin-dot ${!custom&&sel===i?'active':''} ${locked?'locked':''}" data-skin="${i}" ${locked?'disabled':''} style="background:${i===0?base[0]:i===1?'#111820':'linear-gradient(135deg,#fff,#8dd8ff,#ddd)'}" title="${locked?'BLOQUEADA · ':''}${title}"></button>`;}).join('')+(liv?`<button class="skin-dot custom-skin ${custom?'active':''}" data-custom-skin="1" style="background:${liv.base||base[0]}" title="Pintura personalizada">✦</button>`:'');skins.querySelectorAll('[data-skin]:not(:disabled)').forEach(b=>b.onclick=()=>{career.selectedSkin[car.id]=Number(b.dataset.skin);if(career.liveries&&career.liveries[car.id])career.liveries[car.id].active=false;saveCareer();renderGarage();});const customBtn=skins.querySelector('[data-custom-skin]');if(customBtn)customBtn.onclick=()=>{career.liveries[car.id].active=true;saveCareer();renderGarage();};
    const list=document.getElementById('upgradesList');list.innerHTML='';for(const k in UPG){const u=UPG[k],lv=career.upgrades[k],cost=upgradeCost(k),max=lv>=u.max,row=document.createElement('div');row.className='upgrade-row';row.innerHTML=`<div><div class="upgrade-title">${u.name} · Nv.${lv}/${u.max}</div><div class="upgrade-desc">${u.desc}<div class="bar"><span style="width:${lv/u.max*100}%"></span></div></div></div><button class="btn small" data-upg="${k}" ${max||career.money<cost?'disabled':''}>${max?'MÁX':money(cost)}</button>`;list.appendChild(row);}list.querySelectorAll('[data-upg]').forEach(b=>b.addEventListener('click',()=>buyUpgrade(b.getAttribute('data-upg'))));drawGarageCarPreview();
}
globalThis.drawGarageCarPreview = function drawGarageCarPreview() { const car = CARS[garageCarView]; const g = garageCtx; const w = garageCarCanvas.width, h = garageCarCanvas.height; g.imageSmoothingEnabled = false; const bg = g.createLinearGradient(0,0,0,h); bg.addColorStop(0,'#58d1ef'); bg.addColorStop(.48,'#a7f2ff'); bg.addColorStop(.49,'#16a821'); bg.addColorStop(1,'#0d7915'); g.fillStyle = bg; g.fillRect(0,0,w,h); g.fillStyle = '#5f6066'; g.beginPath(); g.moveTo(w*.28,h); g.lineTo(w*.72,h); g.lineTo(w*.58,h*.45); g.lineTo(w*.42,h*.45); g.closePath(); g.fill(); g.save(); const paint=carPaint(car);drawCarGeneric(g,w/2,h*.77,132,paint.color,true,Math.sin(Date.now()*.002)*.55,{model:car.model,stripe:paint.stripe,livery:carLivery(car.id),damage:career.carDamage[car.id]||0,upgradeVisuals:career.upgrades},true); g.restore(); }
globalThis.buyUpgrade = function buyUpgrade(k) { const cost = upgradeCost(k); if (career.upgrades[k] >= UPG[k].max || career.money < cost) return; career.money -= cost; career.upgrades[k]++; playSFX('buy'); saveCareer(); renderGarage(); updateStartBadges(); }
globalThis.openStats = function openStats() { gameMode = 'stats'; const vals = { statRaces:career.stats.races, statWins:career.stats.wins, statCups:career.stats.cups, statEarned:money(career.stats.earned), statFichas:Math.floor(career.fichas||0), statBestCombo:'x'+Number(career.stats.bestCombo||1).toFixed(1), statRiskScore:Math.floor(career.stats.riskScore||0).toLocaleString('pt-BR') }; Object.keys(vals).forEach(id => document.getElementById(id).innerText = vals[id]); let g=0,s=0,b=0; Object.values(career.medals).forEach(m => { if (m === 'gold') g++; else if (m === 'silver') s++; else if (m === 'bronze') b++; }); document.getElementById('statGold').innerText = g; document.getElementById('statSilver').innerText = s; document.getElementById('statBronze').innerText = b; showMenu('stats'); }
globalThis.backFromGarage = function backFromGarage() { if (garageReturn === 'pause') { gamePaused = true; showMenu('pause'); } else if (garageReturn === 'prerace') openPreRace(); else { gameMode = 'menu'; showMenu('start'); } }
globalThis.applyV43AudioSettings = function applyV43AudioSettings(){const mgr=window.RetroRacerAudioManagerV39;if(mgr&&mgr.setVolume){mgr.setVolume('music',career.settings.music);mgr.setVolume('sfx',career.settings.sfx);}}
globalThis.renderSettings = function renderSettings(){const music=document.getElementById('settingMusic'),sfx=document.getElementById('settingSfx');music.value=Math.round(career.settings.music*100);sfx.value=Math.round(career.settings.sfx*100);document.getElementById('settingMusicValue').textContent=music.value+'%';document.getElementById('settingSfxValue').textContent=sfx.value+'%';document.getElementById('qualityLabel').textContent=career.settings.quality;['Low','Med','High','Crt'].forEach(n=>{const e=document.getElementById('btnQuality'+n);if(e)e.classList.toggle('active',career.settings.quality===n.toUpperCase());});document.getElementById('settingFps').value=String(career.settings.fpsCap);document.getElementById('settingSensitivity').value=Math.round(career.settings.sensitivity*100);document.getElementById('settingSensitivityValue').textContent=Math.round(career.settings.sensitivity*100)+'%';document.getElementById('settingDeadzone').value=Math.round(career.settings.deadzone*100);document.getElementById('settingDeadzoneValue').textContent=Math.round(career.settings.deadzone*100)+'%';document.getElementById('settingVirtualButtons').checked=!!career.settings.virtualButtons;document.getElementById('settingAI').value=career.settings.aiMode;document.getElementById('settingDifficulty').value=career.settings.difficulty;document.getElementById('settingControlMode').value=career.settings.controlMode||'PADRAO';document.getElementById('settingHud').value=career.settings.hudSize;document.getElementById('settingReducedFlash').checked=!!career.settings.reducedFlash;document.getElementById('settingColorblind').value=career.settings.colorblind||'OFF';document.getElementById('settingLeftHanded').checked=!!career.settings.leftHanded;document.getElementById('settingButtonScale').value=Math.round((career.settings.buttonScale||1)*100);document.getElementById('settingButtonScaleValue').textContent=Math.round((career.settings.buttonScale||1)*100)+'%';document.getElementById('settingSteerAssist').value=career.settings.steerAssist||'OFF';document.getElementById('settingCaptions').checked=career.settings.captions!==false;const to=document.getElementById('settingTelemetryOptIn');if(to)to.checked=!!career.settings.telemetryOptIn;const te=document.getElementById('settingTelemetryEndpoint');if(te)te.value=career.settings.telemetryEndpoint||'';applyUiSettings();}
globalThis.openSettings = function openSettings(){gameMode='settings';renderSettings();showMenu('settings');}
globalThis.setQuality = function setQuality(q){career.settings.quality=['LOW','MED','HIGH','CRT'].includes(q)?q:'HIGH';runtimeQuality=null;saveCareer();renderSettings();}


globalThis.openCups = async function openCups(){if(window.RRCore&&window.RRCore.assets&&!window.RRCore.assets.trackCatalogReady()){setRaceMessage('CARREGANDO 999 PISTAS…','#38d5ff',.8);await window.RRCore.assets.ensureTrackCatalog();}gameMode='cups';const grid=document.getElementById('cupsGrid');grid.innerHTML='';for(let cup=1;cup<=37;cup++){const circuits=getCupCircuits(cup),first=(cup-1)*27+1,unlocked=cupUnlocked(cup),medals=circuits.map(c=>career.medals[c.id]||'none'),gold=medals.filter(m=>m==='gold').length,silver=medals.filter(m=>m==='silver').length,bronze=medals.filter(m=>m==='bronze').length,biomes=[...new Set(circuits.map(c=>String(c.biome||'').toUpperCase()).filter(Boolean))].join('/');const b=document.createElement('button');b.className='cup-card '+(unlocked?'unlocked':'locked');b.disabled=!unlocked;b.innerHTML=`<div class="cup-num">COPA ${String(cup).padStart(2,'0')} · ${biomes||'MISTO'}</div><div class="cup-name">${circuits[0]?circuits[0].cupName:'Copa '+cup}</div><div class="cup-meta">🥇${gold} · 🥈${silver} · 🥉${bronze}<br>${Math.max(0,Math.min(27,career.level-first+((cup===37&&career.trophies[37])?1:0)))}/27 progresso · ${career.trophies[cup]?'🏆 TROFÉU':unlocked?'ABERTA':'🔒 Fase '+first}</div>`;b.onclick=()=>openTracks(cup);grid.appendChild(b);}showMenu('cups');}
globalThis.openTracks = function openTracks(cup){selectedCup=cup;gameMode='tracks';const circuits=getCupCircuits(cup),title=document.getElementById('tracksCupTitle');title.textContent=(circuits[0]?circuits[0].cupName:'COPA '+cup).toUpperCase();const grid=document.getElementById('tracksGrid');grid.innerHTML='';selectedTrackLevel=Math.max((cup-1)*27+1,Math.min(career.level,cup*27));circuits.forEach(c=>{const unlocked=c.id<=career.level,b=document.createElement('button');b.className='track-card '+(c.id===selectedTrackLevel?'active':'');b.disabled=!unlocked;b.innerHTML=`<b>${String(c.cupRace).padStart(2,'0')} · ${c.name}</b><div class="track-meta">${medalSymbol(career.medals[c.id])} ${c.weatherLabel} · ${c.timeOfDay}<br>BEST ${formatTime(Number(career.records[c.id]||Infinity))}</div>`;b.onclick=()=>{selectedTrackLevel=c.id;grid.querySelectorAll('.track-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawRibbon(document.getElementById('tracksPreview'),c);};grid.appendChild(b);});const active=getCircuitDefinition(selectedTrackLevel);drawRibbon(document.getElementById('tracksPreview'),active);showMenu('tracks');}
globalThis.openTrophies = async function openTrophies(){if(window.RRCore&&window.RRCore.assets&&!window.RRCore.assets.trackCatalogReady())await window.RRCore.assets.ensureTrackCatalog();gameMode='trophies';const grid=document.getElementById('trophiesGrid');grid.innerHTML='';for(let cup=1;cup<=37;cup++){const circuits=getCupCircuits(cup),g=circuits.filter(c=>career.medals[c.id]==='gold').length,earned=!!career.trophies[cup]||g===27;const d=document.createElement('div');d.className='trophy-card';d.innerHTML=`<div style="font-size:28px;text-align:center">${earned?'🏆':'🔒'}</div><div class="cup-name">COPA ${cup}</div><div class="cup-meta">${g}/27 ouros</div>`;grid.appendChild(d);}showMenu('trophies');}
window.RRCore.runtime.bind('almanacCup',1);
globalThis.drawAlmanacMini = function drawAlmanacMini(canvas,circuit,unlocked){const g=canvas.getContext('2d'),w=canvas.width,h=canvas.height;g.clearRect(0,0,w,h);g.fillStyle='#03050a';g.fillRect(0,0,w,h);if(!unlocked||!circuit){g.fillStyle='#2d3240';g.font='900 20px monospace';g.textAlign='center';g.fillText('?',w/2,h*.62);return;}const secs=circuit.sections||[];if(!secs.length)return;const total=secs.reduce((a,x)=>a+(x.e||0)+(x.h||0)+(x.l||0),0)||1;let prog=0,x=w*.08,y=h*.55;g.strokeStyle=career.medals[circuit.id]==='gold'?'#ffcc00':'#38d5ff';g.lineWidth=3;g.lineCap='round';g.beginPath();g.moveTo(x,y);secs.forEach(sec=>{const len=((sec.e||0)+(sec.h||0)+(sec.l||0))/total*(w*.82);prog+=len;y=Math.max(h*.18,Math.min(h*.82,y+Number(sec.c||0)*1.45));x=w*.08+prog;g.lineTo(x,y);});g.stroke();}
globalThis.renderAlmanac = function renderAlmanac(){almanacCup=Math.max(1,Math.min(37,almanacCup));const circuits=getCupCircuits(almanacCup),grid=document.getElementById('almanacGrid');grid.innerHTML='';const discovered=Math.min(999,career.level+((career.level===999&&career.trophies[37])?0:0));document.getElementById('almanacProgress').textContent=`${discovered}/999 pistas descobertas · silhuetas liberadas pela carreira`;document.getElementById('almanacCupTitle').textContent=`COPA ${String(almanacCup).padStart(2,'0')} · ${circuits[0]?circuits[0].cupName:''}`;circuits.forEach(c=>{const unlocked=c.id<=career.level;const d=document.createElement('div');d.className='almanac-card '+(unlocked?'':'locked');d.innerHTML=`<canvas class="almanac-mini" width="180" height="52"></canvas><div class="almanac-meta"><b>${unlocked?String(c.id).padStart(3,'0')+' · '+c.name:'??? · PISTA BLOQUEADA'}</b><br>${unlocked?`${medalSymbol(career.medals[c.id])} ${c.weatherLabel} · ${c.timeOfDay}`:`Desbloqueia na fase ${c.id}`}</div>`;grid.appendChild(d);drawAlmanacMini(d.querySelector('canvas'),c,unlocked);});}
globalThis.openAlmanac = async function openAlmanac(){if(window.RRCore&&window.RRCore.assets&&!window.RRCore.assets.trackCatalogReady())await window.RRCore.assets.ensureTrackCatalog();gameMode='almanac';almanacCup=Math.max(1,Math.min(37,Math.ceil(career.level/27)));renderAlmanac();showMenu('almanac');}
globalThis.openModes = function openModes(){gameMode='modes';setupDailyContracts();const modes=[['licenses','LICENÇAS','60 provas de 20–40 s · aprenda dominando'],['season','TEMPORADA','28 dias · pista diária · gauntlet semanal · passe 40'],['rift','FENDA','5 pistas · dano/fuel persistem · cartas de risco'],['quick','CORRIDA RÁPIDA','Escolha copa, pista e 3–12 voltas'],['timeTrial','TIME TRIAL','Sem rivais · ghost local 20 Hz'],['endurance','ENDURANCE','15 voltas · 2 pits obrigatórios'],['daily','DESAFIO DIÁRIO','Seed local YYYYMMDD'],['boss','BOSS 1v1','Você contra GHOST']];const grid=document.getElementById('modesGrid');grid.innerHTML='';modes.forEach(([id,name,desc])=>{const b=document.createElement('button');b.className='mode-card';b.innerHTML=`<b>${name}</b><div class="track-meta">${desc}</div>`;b.onclick=()=>startMode(id);grid.appendChild(b);});const dl=dailyLevel(),dc=getCircuitDefinition(dl);document.getElementById('dailyInfo').innerHTML=`HOJE: Fase ${dl} · ${dc?dc.name:''}<br>`+(career.contracts.items||[]).map(c=>`<div class="contract">${c.done?'✅':'⬜'} ${c.text}</div>`).join('');showMenu('modes');}
globalThis.startMode = function startMode(mode){if(mode==='licenses'){openLicenses();return;}if(mode==='season'){openSeason();return;}if(mode==='rift'){openRift();return;}raceContext={mode,selectedLevel:career.level,replay:false,laps:5,dailySeed:null,ghost:false,boss:false,insurance:false};if(['quick','timeTrial','endurance'].includes(mode)){trackSelectionMode=mode;raceContext.mode=mode;raceContext.selectedLevel=career.level;if(mode==='timeTrial')raceContext.ghost=true;if(mode==='endurance')raceContext.laps=15;openCups();return;}if(mode==='daily'){raceContext.selectedLevel=dailyLevel();raceContext.dailySeed=localDateKey();}if(mode==='boss'){raceContext.boss=true;raceContext.selectedLevel=Math.min(999,Math.max(27,Math.ceil(career.level/27)*27));}openPreRace(raceContext.selectedLevel,raceContext.mode);}
globalThis.chooseCareer = function chooseCareer(){raceContext={mode:'career',selectedLevel:career.level,replay:false,laps:5,insurance:false};openPreRace(career.level,'career');}

document.getElementById('btnCareer').onclick = chooseCareer;
document.getElementById('btnCups').onclick = () => { trackSelectionMode='career'; openCups(); }; document.getElementById('btnModes').onclick=openModes; document.getElementById('btnTrophies').onclick=openTrophies; document.getElementById('btnAlmanac').onclick=openAlmanac;
document.getElementById('btnCupsBack').onclick=()=>{gameMode='menu';showMenu('start');};document.getElementById('btnAlmanacBack').onclick=()=>{gameMode='menu';showMenu('start');};document.getElementById('btnAlmanacPrev').onclick=()=>{almanacCup=almanacCup<=1?37:almanacCup-1;renderAlmanac();};document.getElementById('btnAlmanacNext').onclick=()=>{almanacCup=almanacCup>=37?1:almanacCup+1;renderAlmanac();};document.getElementById('btnTracksBack').onclick=openCups;document.getElementById('btnTrackRace').onclick=()=>{const mode=['quick','timeTrial','endurance'].includes(trackSelectionMode)?trackSelectionMode:'career';raceContext={mode,selectedLevel:selectedTrackLevel,replay:mode==='career'&&selectedTrackLevel!==career.level,laps:mode==='endurance'?15:5,ghost:mode==='timeTrial',boss:false,insurance:false};openPreRace(selectedTrackLevel,mode);};document.getElementById('btnTrophiesBack').onclick=()=>{gameMode='menu';showMenu('start');};document.getElementById('btnModesBack').onclick=()=>{gameMode='menu';showMenu('start');};document.getElementById('btnCreditsMenu').onclick=()=>{gameMode='menu';showMenu('start');};
document.getElementById('btnGarage').onclick = () => openGarage('start');
document.getElementById('btnStats').onclick = openStats; document.getElementById('btnGhostDossier').onclick=openGhostDossier; document.getElementById('btnGhostDossierBack').onclick=()=>{gameMode='menu';showMenu('start');};
document.getElementById('btnSettings').onclick = openSettings; const ecoBtn=document.getElementById('btnEconomy');if(ecoBtn)ecoBtn.onclick=()=>openEconomy();
document.getElementById('btnSettingsBack').onclick = () => { gameMode = 'menu'; showMenu('start'); };
document.getElementById('btnQualityLow').onclick = () => setQuality('LOW');
document.getElementById('btnQualityHigh').onclick = () => setQuality('HIGH');
document.getElementById('btnQualityMed').onclick=()=>setQuality('MED'); document.getElementById('btnQualityCrt').onclick=()=>setQuality('CRT');
document.getElementById('settingFps').onchange=e=>{career.settings.fpsCap=Number(e.target.value)===30?30:60;saveCareer();};
document.getElementById('settingSensitivity').oninput=e=>{career.settings.sensitivity=Number(e.target.value)/100;document.getElementById('settingSensitivityValue').textContent=e.target.value+'%';saveCareer();};
document.getElementById('settingDeadzone').oninput=e=>{career.settings.deadzone=Number(e.target.value)/100;document.getElementById('settingDeadzoneValue').textContent=e.target.value+'%';saveCareer();};
document.getElementById('settingVirtualButtons').onchange=e=>{career.settings.virtualButtons=e.target.checked;saveCareer();applyUiSettings();}; document.getElementById('btnShowTouchHint').onclick=()=>{career.flags.touchHintSeen=false;saveCareer();touchHint.classList.remove('hidden');setTimeout(()=>touchHint.classList.add('hidden'),6500);};
document.getElementById('settingAI').onchange=e=>{career.settings.aiMode=e.target.value;saveCareer();}; document.getElementById('settingControlMode').onchange=e=>{career.settings.controlMode=e.target.value==='COPILOTO'?'COPILOTO':'PADRAO';career.flags.c14DriveModes=true;saveCareer();applyUiSettings();}; document.getElementById('settingDifficulty').onchange=e=>{career.settings.difficulty=e.target.value;saveCareer();}; document.getElementById('settingHud').onchange=e=>{career.settings.hudSize=e.target.value;saveCareer();applyUiSettings();}; document.getElementById('settingReducedFlash').onchange=e=>{career.settings.reducedFlash=e.target.checked;career.flags.c18Accessibility=true;saveCareer();applyUiSettings();}; document.getElementById('settingColorblind').onchange=e=>{career.settings.colorblind=e.target.value;career.flags.c18Accessibility=true;saveCareer();applyUiSettings();}; document.getElementById('settingLeftHanded').onchange=e=>{career.settings.leftHanded=e.target.checked;career.flags.c18Accessibility=true;saveCareer();applyUiSettings();}; document.getElementById('settingButtonScale').oninput=e=>{career.settings.buttonScale=MathUtils.limit(Number(e.target.value)/100,.8,1.4);document.getElementById('settingButtonScaleValue').textContent=e.target.value+'%';career.flags.c18Accessibility=true;saveCareer();applyUiSettings();}; document.getElementById('settingSteerAssist').onchange=e=>{career.settings.steerAssist=e.target.value;career.flags.c18Accessibility=true;saveCareer();}; document.getElementById('settingCaptions').onchange=e=>{career.settings.captions=e.target.checked;career.flags.c18Accessibility=true;saveCareer();applyUiSettings();};
const telOpt=document.getElementById('settingTelemetryOptIn');if(telOpt)telOpt.onchange=e=>{career.settings.telemetryOptIn=e.target.checked;saveCareer();};const telEnd=document.getElementById('settingTelemetryEndpoint');if(telEnd)telEnd.onchange=e=>{career.settings.telemetryEndpoint=String(e.target.value||'').trim().slice(0,240);saveCareer();};
document.getElementById('preTireSelect').onchange=e=>{career.settings.tire=e.target.value;saveCareer();};
document.getElementById('preInsurance').onchange=e=>{raceContext.insurance=e.target.checked;};
document.getElementById('preLapsSelect').onchange=e=>{raceContext.laps=Math.floor(clampNumber(e.target.value,3,12,5));totalLaps=raceContext.laps;document.getElementById('preLaps').innerText=String(totalLaps);buildTrack();document.getElementById('preGold').innerText=formatTime(targetGoldTime);};
document.getElementById('settingMusic').addEventListener('input', (e) => { career.settings.music = MathUtils.limit(Number(e.target.value)/100,0,1); document.getElementById('settingMusicValue').textContent = e.target.value + '%'; saveCareer(); applyV43AudioSettings(); });
document.getElementById('settingSfx').addEventListener('input', (e) => { career.settings.sfx = MathUtils.limit(Number(e.target.value)/100,0,1); document.getElementById('settingSfxValue').textContent = e.target.value + '%'; saveCareer(); applyV43AudioSettings(); });
document.getElementById('btnHelp').onclick = () => { gameMode = 'help'; showMenu('help'); };
document.getElementById('btnHelpBack').onclick = () => { gameMode = 'menu'; showMenu('start'); };
document.getElementById('btnStatsBack').onclick = () => { gameMode = 'menu'; showMenu('start'); };
document.getElementById('btnStartRace').onclick = startRace;
document.getElementById('btnPreGarage').onclick = () => openGarage('prerace');
document.getElementById('btnPreBack').onclick = () => { if(raceContext.mode==='shadow'&&globalThis.shadowOpenMenu){shadowOpenMenu(false);return;}if(raceContext.mode==='license'&&globalThis.openLicenses){openLicenses();return;} gameMode = 'menu'; showMenu('start'); };
document.getElementById('btnCarPrev').onclick = () => { garageCarView = (garageCarView - 1 + CARS.length) % CARS.length; renderGarage(); };
document.getElementById('btnCarNext').onclick = () => { garageCarView = (garageCarView + 1) % CARS.length; renderGarage(); };
document.getElementById('btnSelectBuyCar').onclick = () => { const car = CARS[garageCarView]; if (career.unlockedCars.includes(garageCarView)) { career.selectedCar = garageCarView; } else if (carAvailable(car) && career.money >= car.price) { career.money -= car.price; career.unlockedCars.push(garageCarView); career.selectedCar = garageCarView; playSFX('buy'); } saveCareer(); renderGarage(); updateStartBadges(); };
document.getElementById('btnRepairCar').onclick = () => { const cost = Math.ceil((career.carDamage[garageCarView] || 0) * 2500); if (cost > 0 && career.money >= cost) { career.money -= cost; career.carDamage[garageCarView] = 0; playSFX('buy'); saveCareer(); renderGarage(); updateStartBadges(); } };
document.getElementById('btnGarageBack').onclick = backFromGarage;
document.getElementById('btnResetSave').onclick=()=>{const typed=prompt('Para apagar TODO o progresso, digite CORRIDA');if(typed==='CORRIDA'){[SAVE_KEY,...OLD_KEYS].forEach(k=>localStorage.removeItem(k));location.reload();}else if(typed!==null)alert('Texto incorreto. Save preservado.');};
document.getElementById('btnResume').onclick = () => { gamePaused = false; gameMode = 'race'; showMenu(null); };
document.getElementById('btnPauseGarage').onclick = () => {if(raceContext.mode==='rift'){setRaceMessage('FENDA · SEM GARAGEM ENTRE PISTAS','#ffcc00',1);return;}openGarage('pause');};
document.getElementById('btnQuitRace').onclick = () => { if(raceContext.mode==='rift'&&globalThis.riftAbort)riftAbort('FENDA ABANDONADA');fadeAudioOut(); gameMode = 'menu'; gamePaused = false; showMenu('start'); };
document.getElementById('btnNextRace').onclick=()=>{if(['seasonDaily','seasonGauntlet'].includes(raceContext.mode)&&globalThis.seasonAfterResult){seasonAfterResult();return;}if(raceContext.mode==='rift'&&globalThis.riftAfterResult){riftAfterResult();return;}if(raceLevel===999&&finalPlayerRank===1){showMenu('credits');return;} if(raceContext.mode==='career'&&!raceContext.replay){raceContext.selectedLevel=career.level;openPreRace(career.level,'career');}else openPreRace(raceLevel,raceContext.mode);};
document.getElementById('btnResultsGarage').onclick = () => {if(raceContext.mode==='rift')return;openGarage('start');};
document.getElementById('btnResultsMenu').onclick = () => {if(raceContext.mode==='rift'&&career.fenda?.active&&globalThis.riftAbort)riftAbort('FENDA ABANDONADA'); gameMode = 'menu'; showMenu('start'); };
const rewardDouble=document.getElementById('btnRewardDouble');if(rewardDouble)rewardDouble.onclick=async()=>{if(await economyClaimRewardedDouble()){rewardDouble.classList.add('hidden');setRaceMessage('PRÊMIO DUPLICADO','#55ff88',1.4);}};const rewardContinue=document.getElementById('btnRewardContinue');if(rewardContinue)rewardContinue.onclick=async()=>{if(await economyClaimRiftContinue()){gameOver=false;gameMode='race';showMenu(null);startRace();}};
document.getElementById('btnRetry').onclick = () => {if(raceContext.mode==='rift'){openRift();return;}if(raceContext.mode==='license'&&globalThis.openLicenses){openLicenses();return;}startRace();};
document.getElementById('btnGameOverGarage').onclick = () => {if(raceContext.mode==='rift')return;openGarage('start');};
document.getElementById('btnGameOverMenu').onclick = () => {if(raceContext.mode==='rift'&&career.fenda?.active&&globalThis.riftFail)riftFail('RUN ENCERRADA'); gameMode = 'menu'; showMenu('start'); };

window.RRCore.runtime.bind('lastTime',0);
window.RRCore.runtime.bind('accumulator',0);

document.getElementById('btnRiftBack').onclick=()=>{if(career.fenda?.active&&career.fenda.stageDone===false){/* preserva run para retomar */}openModes();};
