// Rádio vivo C07 — falas só por evento concreto, seleção determinística por evento/seed.
const BANK=Object.freeze({
 start:['ENG: PISTA LIVRE. FAÇA VALER.','ENG: CINCO VOLTAS. CABEÇA FRIA.','ENG: PRIMEIRA CURVA DECIDE O TOM.','ENG: AQUEÇA PNEU, NÃO O EGO.','ENG: SEM HEROÍSMO NA PRIMEIRA FREIADA.','ENG: RELÓGIO RODANDO. VAI.'],
 overtake:['ENG: LIMPO. PRÓXIMO ALVO.','ENG: BOA. NÃO DEVOLVE A POSIÇÃO.','ENG: PASSOU POR MÉRITO.','ENG: PORTA ABERTA, VOCÊ ENTROU.','ENG: GANHOU A LINHA. SEGURA.','ENG: ULTRAPASSAGEM CIRÚRGICA.'],
 lost:['ENG: ELE LEU SUA LINHA. RESPONDA.','ENG: POSIÇÃO PERDIDA. SEM PÂNICO.','ENG: GUARDE O NITRO PARA A RESPOSTA.','ENG: VOCÊ CEDEU A CORDA. RECUPERA.','ENG: RESPIRA. A CORRIDA NÃO ACABOU.','ENG: UM ERRO. NÃO FAÇA DOIS.'],
 pitOpen:['ENG: PIT ABERTO. ENTRADA À DIREITA.','ENG: BOX DISPONÍVEL. REDUZA ANTES DA LINHA.','ENG: JANELA DE PIT AGORA.','ENG: BOX À DIREITA. NÃO CHEGUE VOANDO.','ENG: PIT LIBERADO. FREIO ANTES DA FAIXA.','ENG: EQUIPE PRONTA. ENTRA LIMPO.'],
 pitPerfect:['ENG: SERVIÇO PERFEITO. GO.','ENG: BOX LIMPO. VOLTA PRA BRIGA.','ENG: TANQUE CHEIO. PNEU CERTO. VAI.','ENG: PIT NO PONTO. SEM TEMPO PERDIDO.','ENG: EQUIPE ENTREGOU. SUA VEZ.','ENG: SAÍDA LIMPA. AQUEÇA O PNEU.'],
 fuelLow:['ENG: COMBUSTÍVEL CRÍTICO. PENSE NO PIT.','ENG: TANQUE BAIXO. NITRO CUSTA CARO AGORA.','ENG: ECONOMIZE NA RETA OU ENTRE NO BOX.','ENG: RESERVA ACESA. SEM DESPERDÍCIO.','ENG: GASOLINA NO LIMITE. ESCOLHA SUA JANELA.','ENG: TANQUE GRITANDO. PIT NA PRÓXIMA CHANCE.'],
 finalLap:['ENG: ÚLTIMA VOLTA. TUDO OU NADA.','ENG: BANDEIRA VEM AGORA. SEM SOBRA.','ENG: ÚLTIMA. USE O QUE GUARDOU.','ENG: UMA VOLTA ENTRE VOCÊ E O RESULTADO.','ENG: FINAL LAP. OLHOS NA SAÍDA DAS CURVAS.','ENG: CHEGOU A HORA. ZERO CONSERVADORISMO.'],
 crash:['ENG: IMPACTO FORTE. CARRO AINDA RESPONDE.','ENG: ISSO CUSTOU TEMPO. RECOMPÕE.','ENG: BATIDA REGISTRADA. NÃO REPITA.','ENG: SUSPENSÃO SENTIU. SEGURA A LINHA.','ENG: CARRO VIVO. CORRIDA VIVA.','ENG: TIRA O PÉ UM INSTANTE E VOLTA.'],
 weather:['ENG: CLIMA MUDANDO. LINHA VAI MUDAR JUNTO.','ENG: CHUVA CHEGOU. FREIE RETO.','ENG: PISTA MOLHANDO. EVITE MOVIMENTO BRUSCO.','ENG: ÁGUA NA PISTA. RESPEITE O GRIP.','ENG: PREVISÃO CONFIRMADA. PROCURE ADERÊNCIA.','ENG: ASFALTO VIROU OUTRO JOGO.'],
 podium:['ENG: TOP 3. AGORA A MÚSICA É SUA.','ENG: PÓDIO À VISTA. NÃO ADMINISTRE DEMAIS.','ENG: VOCÊ ENTROU NO PÓDIO. PRESSIONA.','ENG: TRÊS PRIMEIROS. MANTÉM O RITMO.','ENG: PÓDIO PROVISÓRIO. TRANSFORMA EM TROFÉU.','ENG: AGORA ELES ESTÃO OLHANDO VOCÊ.'],
 chase:['ENG: FUNDO DO GRID. CORTE UM POR VEZ.','ENG: TEM CARRO DEMAIS NA SUA FRENTE. TRABALHA.','ENG: RECUPERAÇÃO COMEÇA AGORA.','ENG: ESQUECE O LÍDER. PEGA O PRÓXIMO.','ENG: TRÂNSITO PESADO. PROCURE O VÁCUO.','ENG: POSIÇÃO RUIM, CORRIDA LONGA.'],
 ghost:['GHOST: EU JÁ SEI ONDE VOCÊ FREIA.','GHOST: SUA MELHOR LINHA AGORA É MINHA.','GHOST: VOCÊ ME ENSINOU ISSO.','GHOST: QUATRO POR CENTO É O BASTANTE.','GHOST: CORRI SUA VOLTA ANTES DE VOCÊ.','GHOST: MUDE O HÁBITO OU EU REPITO A VITÓRIA.'],
 rex:['REX: ESSA PORTA FICA FECHADA.','REX: TENTA PELO OUTRO LADO.','REX: MINHA LINHA. ME TIRA DELA.','REX: SEM ESPAÇO PRA VOCÊ AQUI.','REX: EU DEFENDO ATÉ A ZEBRA.','REX: QUER PASSAR? PAGA NA FREIADA.'],
 viper:['VIPER: ESTOU NO SEU RETROVISOR.','VIPER: UMA CURVA E EU CHEGO.','VIPER: GUARDOU NITRO? EU TAMBÉM.','VIPER: NÃO OLHA PRA TRÁS.','VIPER: SUA LINHA ESTÁ FICANDO PEQUENA.','VIPER: ESCUTA O MOTOR. ESTOU AÍ.']
});
const count=Object.create(null),cool=Object.create(null);let lastPodium=false,lastChase=false,lastFuel=false;
function phrase(kind){const a=BANK[kind]||BANK.start,n=count[kind]||0;count[kind]=n+1;return a[(raceLevel*7+n*3)%a.length];}
globalThis.raceRadioEvent=function raceRadioEvent(kind,override='',seconds=1.7){if(cool[kind]>0)return false;const msg=override||phrase(kind);radio(msg,seconds);cool[kind]=kind==='viper'||kind==='rex'?9:kind==='fuelLow'?20:2.2;if(window.RetroRacerAudioManagerV39&&window.RetroRacerAudioManagerV39.duckMusic)window.RetroRacerAudioManagerV39.duckMusic(kind==='crash'?'crash':kind==='pitPerfect'||kind==='pitOpen'?'pit':kind==='finalLap'?'lap':'alarm');return true;};
globalThis.liveRadioTick=function liveRadioTick(dt){for(const k in cool)cool[k]=Math.max(0,cool[k]-dt);if(gameMode!=='race'||!raceStarted||finished||gameOver)return;const pos=lastRacePosition||23,podium=pos<=3,chase=pos>=15;if(podium&&!lastPodium)raceRadioEvent('podium');if(chase&&!lastChase&&totalRaceTime>4)raceRadioEvent('chase');lastPodium=podium;lastChase=chase;if(fuel<calcMods().fuelCapacity*.22&&!lastFuel){lastFuel=true;raceRadioEvent('fuelLow');}if(fuel>calcMods().fuelCapacity*.38)lastFuel=false;};
globalThis.resetLiveRadio=function resetLiveRadio(){for(const k in cool)delete cool[k];for(const k in count)delete count[k];lastPodium=false;lastChase=false;lastFuel=false;};
globalThis.RR_RADIO_BANK=BANK;
