import { CARS, UPG, refreshCarUnlocks } from '../meta/cars.js';
export const SAVE_KEY = 'retro_racer_championship_v30';
export const OLD_KEYS = ['retro_racer_championship_v29','retro_racer_v15','retro_racer_v14','retro_racer_v13'];
export const defaultCareer = {
  version:73,level:1,money:3500,selectedCar:0,unlockedCars:[0],carDamage:{0:0,1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0,10:0,11:0},
  upgrades:{engine:0,tires:0,tank:0,turbo:0,armor:0,suspension:0,brakes:0,radiator:0,ecu:0,aero:0},stats:{races:0,starts:0,wins:0,cups:0,earned:0,ghostWins:0,bossWins:0,dailyWins:0,pits:0,crashes:0,goldStreak:0,bestCombo:0,riskScore:0,fichasEarned:0,riftRuns:0,riftWins:0,riftBestStage:0},
  medals:{},records:{},recordsByCar:{},ghosts:{},trophies:{},bonuses:{},skins:{},selectedSkin:{},liveries:{},coach:{traces:{},last:null},story:{seen:{}},highlight:{exports:0,shares:0,last:null},fichas:0,marcas:0,cosmetics:{trails:['classic'],selectedTrail:'classic'},economy:{ledger:[],founder:false,adFree:false,premiumSeason:false,rewarded:{lastRace:null,riftUsedRun:0},owned:{nitroColors:['classic'],horns:['stock'],labels:['classic'],packs:[]},selected:{nitroColor:'classic',horn:'stock',label:'classic'}},licenses:{medals:{},goldCount:0,attempts:0,lastResult:null},fenda:{active:false,seed:0,stage:0,levels:[],fuel:1,preDamage:0,damage:0,bank:0,choices:[],chosen:[],legendaryStage:0,stageDone:false,completed:false,failed:false,lastResult:''},season:{key:'',xp:0,passLevel:0,daily:{},weekly:{},gauntlet:{key:'',stage:0,levels:[],active:false,score:0},history:[]},contracts:{},telemetry:{lastRaces:[],events:[],sessionDays:[],sessionStart:0},integrity:{recordProofs:{},legacyRecords:{},clock:{lastWall:0,lastGoodDay:'',suspect:false,reason:''}},shadow:{alias:'PILOTO',library:[],lastImport:null,lastExport:null,imports:0,exports:0},ghostProfile:{version:1,races:0,braking:{light:10,medium:10,hairpin:11},brakeSpeed:.62,slipTolerance:.45,aggression:.5,nitroPoint:.5,lineBias:0,errors:{offroad:0,collisions:0},dominantError:'SEM DADOS',lastInsight:'',lastRace:{}},
  settings:{quality:'HIGH',music:0.53,sfx:0.37,aiMode:'CAMPEONATO',difficulty:'NORMAL',controlMode:'PADRAO',hudSize:'M',reducedFlash:false,sensitivity:1.0,deadzone:.08,virtualButtons:false,fpsCap:60,tire:'MISTO',colorblind:'OFF',leftHanded:false,buttonScale:1,steerAssist:'OFF',captions:true,telemetryOptIn:false,telemetryEndpoint:''},
  flags:{v43Juice:true,v44Cups:true,v45Garage:true,v46Weather:true,v47AI:true,v48Modes:true,v49AV:true,v50Platform:true,v51Legendary:true,v52Polish:true,c01DeterministicCore:true,c02InstantDrive:true,c03Juice:true,c04Haptics:true,c05GhostLearns:true,c06ShadowCode:false,c07ReactiveAudio:false,c08RiskCombo:false,c09Rift:false,c10Season:false,c11Licenses:false,c12Paint:false,c13Coach:false,c14DriveModes:false,c15Story:false,c16Highlight:false,c17Identity:false,c18Accessibility:false,c19Economy:false,c20Telemetry:false,c21Integrity:false,monetization:false,ftueComplete:false,ftuePrologueSeen:false,touchHintSeen:false}
};
export const career = structuredClone(defaultCareer);
export function clampNumber(value,min,max,fallback){const n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback;}
function resetObject(target,source){for(const k of Object.keys(target))delete target[k];Object.assign(target,structuredClone(source));}
export function saveCareer(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(career));}catch(e){}}
export function migrateCareer(p){
  resetObject(career,defaultCareer);
  try{
    if(!p||typeof p!=='object')return career;
    career.level=Math.floor(clampNumber(p.level||p.currentLevel,1,999,1));career.money=Math.floor(clampNumber(p.money,0,999999999,defaultCareer.money));career.selectedCar=Math.floor(clampNumber(p.selectedCar,0,CARS.length-1,0));
    career.unlockedCars=Array.isArray(p.unlockedCars)?[...new Set(p.unlockedCars.map(v=>Math.floor(Number(v))).filter(v=>v>=0&&v<CARS.length))]:[0];if(!career.unlockedCars.includes(0))career.unlockedCars.push(0);
    career.carDamage={...defaultCareer.carDamage,...(p.carDamage||{})};career.upgrades={...defaultCareer.upgrades,...(p.upgrades||{})};if(career.upgrades.fuelTank!==undefined&&career.upgrades.tank===0)career.upgrades.tank=career.upgrades.fuelTank;for(const k in UPG)career.upgrades[k]=Math.floor(clampNumber(career.upgrades[k],0,UPG[k].max,0));
    career.stats={...defaultCareer.stats,...(p.stats||{})};for(const k of ['medals','records','recordsByCar','ghosts','trophies','bonuses','skins','selectedSkin','contracts'])career[k]=p[k]&&typeof p[k]==='object'?p[k]:{};career.liveries=p.liveries&&typeof p.liveries==='object'?structuredClone(p.liveries):{};career.coach={...structuredClone(defaultCareer.coach),...(p.coach||{})};career.coach.traces=p.coach&&p.coach.traces&&typeof p.coach.traces==='object'?p.coach.traces:{};career.story={...structuredClone(defaultCareer.story),...(p.story||{})};career.story.seen=p.story&&p.story.seen&&typeof p.story.seen==='object'?p.story.seen:{};career.highlight={...structuredClone(defaultCareer.highlight),...(p.highlight||{})};career.fichas=Math.floor(clampNumber(p.fichas,0,9999999,0));career.marcas=Math.floor(clampNumber(p.marcas,0,9999999,0));career.economy={...structuredClone(defaultCareer.economy),...(p.economy||{})};career.economy.ledger=Array.isArray(career.economy.ledger)?career.economy.ledger.slice(-120):[];career.economy.rewarded={...defaultCareer.economy.rewarded,...((p.economy&&p.economy.rewarded)||{})};career.economy.owned={...structuredClone(defaultCareer.economy.owned),...((p.economy&&p.economy.owned)||{})};for(const k of ['nitroColors','horns','labels','packs'])career.economy.owned[k]=Array.isArray(career.economy.owned[k])?[...new Set(career.economy.owned[k].map(String))]:structuredClone(defaultCareer.economy.owned[k]);career.economy.selected={...defaultCareer.economy.selected,...((p.economy&&p.economy.selected)||{})};career.cosmetics={...structuredClone(defaultCareer.cosmetics),...(p.cosmetics||{})};career.cosmetics.trails=Array.isArray(career.cosmetics.trails)?[...new Set(['classic',...career.cosmetics.trails.map(String)])]:['classic'];if(!career.cosmetics.trails.includes(career.cosmetics.selectedTrail))career.cosmetics.selectedTrail='classic';career.licenses={...structuredClone(defaultCareer.licenses),...(p.licenses||{})};career.licenses.medals=p.licenses&&p.licenses.medals&&typeof p.licenses.medals==='object'?p.licenses.medals:{};career.licenses.goldCount=Object.values(career.licenses.medals).filter(v=>v==='gold').length;career.licenses.attempts=Math.floor(clampNumber(career.licenses.attempts,0,999999,0));
    career.fenda={...structuredClone(defaultCareer.fenda),...(p.fenda||{})};career.fenda.levels=Array.isArray(career.fenda.levels)?career.fenda.levels.map(v=>Math.floor(clampNumber(v,1,999,1))).slice(0,5):[];career.fenda.choices=Array.isArray(career.fenda.choices)?career.fenda.choices.slice(0,3):[];career.fenda.chosen=Array.isArray(career.fenda.chosen)?career.fenda.chosen.slice(0,5):[];career.season={...structuredClone(defaultCareer.season),...(p.season||{})};career.season.daily=p.season&&p.season.daily&&typeof p.season.daily==='object'?p.season.daily:{};career.season.weekly=p.season&&p.season.weekly&&typeof p.season.weekly==='object'?p.season.weekly:{};career.season.gauntlet={...structuredClone(defaultCareer.season.gauntlet),...((p.season&&p.season.gauntlet)||{})};career.season.gauntlet.levels=Array.isArray(career.season.gauntlet.levels)?career.season.gauntlet.levels.map(v=>Math.floor(clampNumber(v,1,999,1))).slice(0,3):[];career.season.history=Array.isArray(career.season.history)?career.season.history.slice(-4):[];career.season.xp=Math.floor(clampNumber(career.season.xp,0,999999,0));career.season.passLevel=Math.floor(clampNumber(career.season.passLevel,0,40,0));
    if((career.stats.goldStreak||0)>=3||Object.values(career.selectedSkin).some(v=>Number(v)===2))career.skins.chromeUnlocked=true;
    career.telemetry={...structuredClone(defaultCareer.telemetry),...(p.telemetry||{})};if(!Array.isArray(career.telemetry.lastRaces))career.telemetry.lastRaces=[];if(!Array.isArray(career.telemetry.events))career.telemetry.events=[];career.telemetry.events=career.telemetry.events.slice(-500);if(!Array.isArray(career.telemetry.sessionDays))career.telemetry.sessionDays=[];career.telemetry.sessionDays=[...new Set(career.telemetry.sessionDays.map(String))].slice(-120);career.integrity={...structuredClone(defaultCareer.integrity),...(p.integrity||{})};career.integrity.recordProofs=p.integrity&&p.integrity.recordProofs&&typeof p.integrity.recordProofs==='object'?p.integrity.recordProofs:{};career.integrity.legacyRecords=p.integrity&&p.integrity.legacyRecords&&typeof p.integrity.legacyRecords==='object'?p.integrity.legacyRecords:{};career.integrity.clock={...defaultCareer.integrity.clock,...((p.integrity&&p.integrity.clock)||{})};if(Object.keys(career.integrity.recordProofs).length===0&&p.records&&typeof p.records==='object')career.integrity.legacyRecords={...p.records,...career.integrity.legacyRecords};career.shadow={...structuredClone(defaultCareer.shadow),...(p.shadow||{})};career.shadow.alias=String(career.shadow.alias||'PILOTO').slice(0,16);career.shadow.library=Array.isArray(career.shadow.library)?career.shadow.library.slice(0,12):[];career.ghostProfile={...structuredClone(defaultCareer.ghostProfile),...(p.ghostProfile||{})};career.ghostProfile.braking={...defaultCareer.ghostProfile.braking,...((p.ghostProfile&&p.ghostProfile.braking)||{})};career.ghostProfile.errors={...defaultCareer.ghostProfile.errors,...((p.ghostProfile&&p.ghostProfile.errors)||{})};career.ghostProfile.lastRace={...((p.ghostProfile&&p.ghostProfile.lastRace)||{})};
    career.settings={...defaultCareer.settings,...(p.settings||{})};const q=String(career.settings.quality||'HIGH').toUpperCase();career.settings.quality=['LOW','MED','HIGH','CRT'].includes(q)?q:'HIGH';career.settings.music=clampNumber(career.settings.music,0,1,.53);career.settings.sfx=clampNumber(career.settings.sfx,0,1,.37);career.settings.sensitivity=clampNumber(career.settings.sensitivity,.5,1.5,1);career.settings.deadzone=clampNumber(career.settings.deadzone,0,.3,.08);career.settings.fpsCap=Number(career.settings.fpsCap)===30?30:60;career.settings.virtualButtons=!!career.settings.virtualButtons;career.settings.reducedFlash=!!career.settings.reducedFlash;career.settings.aiMode=career.settings.aiMode==='FIXA'?'FIXA':'CAMPEONATO';career.settings.hudSize=['S','M','L'].includes(career.settings.hudSize)?career.settings.hudSize:'M';career.settings.difficulty=['FACIL','NORMAL','HEROI','LENDA'].includes(career.settings.difficulty)?career.settings.difficulty:'NORMAL';career.settings.controlMode=career.settings.controlMode==='COPILOTO'?'COPILOTO':'PADRAO';career.settings.tire=['SLICK','MISTO','CHUVA'].includes(career.settings.tire)?career.settings.tire:'MISTO';career.settings.colorblind=['OFF','PROTAN','DEUTER','TRITAN'].includes(String(career.settings.colorblind).toUpperCase())?String(career.settings.colorblind).toUpperCase():'OFF';career.settings.leftHanded=!!career.settings.leftHanded;career.settings.buttonScale=clampNumber(career.settings.buttonScale,.8,1.4,1);career.settings.steerAssist=['OFF','LEVE','MEDIO','FORTE'].includes(String(career.settings.steerAssist).toUpperCase())?String(career.settings.steerAssist).toUpperCase():'OFF';career.settings.captions=career.settings.captions!==false;career.settings.telemetryOptIn=!!career.settings.telemetryOptIn;career.settings.telemetryEndpoint=String(career.settings.telemetryEndpoint||'').slice(0,240);
    career.flags={...defaultCareer.flags,...(p.flags||{})};career.flags.monetization=!!career.flags.monetization;career.version=73;refreshCarUnlocks(career);if(!career.unlockedCars.includes(career.selectedCar))career.selectedCar=0;return career;
  }catch(e){console.warn('Save antigo inválido; mantendo defaults.',e);return career;}
}
export function loadCareer(){
  try{let raw=null;for(const k of [SAVE_KEY,...OLD_KEYS]){raw=localStorage.getItem(k);if(raw)break;}return raw?migrateCareer(JSON.parse(raw)):migrateCareer(null);}catch(e){return migrateCareer(null);}
}
export function clearCareer(){for(const k of [SAVE_KEY,...OLD_KEYS])localStorage.removeItem(k);resetObject(career,defaultCareer);return career;}
