// CICLO 16 — buffer circular de 8 s + clipe vertical 9:16, 100% local.
const CLIP_HZ=20,CLIP_SECONDS=8,CAP=CLIP_HZ*CLIP_SECONDS;
const inputBuf=new Uint8Array(CAP),speedBuf=new Uint8Array(CAP),xBuf=new Int8Array(CAP);let head=0,count=0,best=null,raceMeta=null,previewRaf=0,previewStart=0,lastBlob=null;
const KIND_SCORE={finish:45,overtake:62,combo:72,ghost:95,photo:110};
function pack(steer,accel,brake,nitro){let q=Math.max(0,Math.min(15,Math.round((Math.max(-1,Math.min(1,Number(steer)||0))+1)*7.5)));if(accel)q|=16;if(brake)q|=32;if(nitro)q|=64;return q;}
function unpack(v){return{steer:(v&15)/7.5-1,accel:!!(v&16),brake:!!(v&32),nitro:!!(v&64)};}
function snapshot(){const n=count,a=new Uint8Array(n),s=new Uint8Array(n),x=new Int8Array(n),start=(head-n+CAP)%CAP;for(let i=0;i<n;i++){const j=(start+i)%CAP;a[i]=inputBuf[j];s[i]=speedBuf[j];x[i]=xBuf[j];}return{input:a,speed:s,x};}
function trackName(){return activeCircuit?.name||`FASE ${String(raceLevel).padStart(3,'0')}`;}
function codeForClip(){try{const p=globalThis.shadowGetSharePackage?.(true);return p?.code||career.shadow?.lastExport?.code||`RR7-F${String(raceLevel).padStart(3,'0')}`;}catch(e){return career.shadow?.lastExport?.code||`RR7-F${String(raceLevel).padStart(3,'0')}`;}}
function mark(kind,label='',score=null){if(!raceMeta||count<8)return false;const sc=Number(score??KIND_SCORE[kind]??40);if(best&&sc<=best.score)return false;best={kind,label:label||kind.toUpperCase(),score:sc,frames:snapshot(),at:totalRaceTime};return true;}
globalThis.highlightRaceStart=function highlightRaceStart(){head=0;count=0;best=null;lastBlob=null;raceMeta={level:raceLevel,mode:raceContext.mode,car:currentCar().name,color:carPaint(currentCar()).color,stripe:carPaint(currentCar()).stripe,track:trackName(),started:Date.now()};};
globalThis.highlightCaptureInput=function highlightCaptureInput(steer,accel,brake,nitro){if(!raceMeta||!raceStarted||finished||gameOver)return;inputBuf[head]=pack(steer,accel,brake,nitro);speedBuf[head]=Math.max(0,Math.min(255,Math.round((speed/Math.max(1,maxSpeed))*220)));xBuf[head]=Math.max(-127,Math.min(127,Math.round(playerX*70)));head=(head+1)%CAP;count=Math.min(CAP,count+1);};
globalThis.highlightMark=function highlightMark(kind,label,score){return mark(kind,label,score);};
globalThis.highlightRaceFinish=function highlightRaceFinish(photo,gap,rank){if(photo)mark('photo',`FOTO FINISH · ${Number(gap).toFixed(2)}s`,KIND_SCORE.photo);else if(!best)mark('finish',rank===1?'VITÓRIA NO HORIZONTE':'CHEGADA',KIND_SCORE.finish);const code=codeForClip();const clip=best||{kind:'finish',label:'CHEGADA',score:40,frames:snapshot(),at:totalRaceTime};clip.meta={...raceMeta,rank,code,time:finalTotalTime};career.highlight.last={kind:clip.kind,label:clip.label,level:raceLevel,code,frames:clip.frames.input.length};career.flags.c16Highlight=true;saveCareer();best=clip;return clip;};
function roadPath(c,w,h,steer,t){const horizon=h*.34,bottom=h*.89,curve=steer*w*.11+Math.sin(t*.0007)*w*.018;c.fillStyle='#181a22';c.beginPath();c.moveTo(w*.43+curve*.1,horizon);c.lineTo(w*.57+curve*.1,horizon);c.lineTo(w*.94+curve,bottom);c.lineTo(w*.06+curve,bottom);c.closePath();c.fill();c.strokeStyle='#fff0c4';c.lineWidth=2;c.setLineDash([10,13]);c.beginPath();c.moveTo(w*.5+curve*.12,horizon);c.lineTo(w*.5+curve,bottom);c.stroke();c.setLineDash([]);}
function renderFrame(canvas,clip,idx,clock=0){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,n=Math.max(1,clip.frames.input.length),i=Math.max(0,Math.min(n-1,idx|0)),f=unpack(clip.frames.input[i]||0),sp=(clip.frames.speed[i]||0)/220,px=(clip.frames.x[i]||0)/70;c.imageSmoothingEnabled=false;const g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,'#071329');g.addColorStop(.45,'#16385d');g.addColorStop(1,'#05060a');c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle='#ffcc00';c.globalAlpha=.18;c.beginPath();c.arc(w*.78,h*.17,w*.12,0,Math.PI*2);c.fill();c.globalAlpha=1;for(let k=0;k<18;k++){c.fillStyle=k%2?'#091726':'#0b2030';const bw=20+(k*13)%45,bh=30+(k*17)%100,x=(k*71+clip.meta.level*19)%w;c.fillRect(x,h*.24-bh,bw,bh);}roadPath(c,w,h,f.steer,clock);if(f.nitro||sp>.92){c.strokeStyle='rgba(255,255,255,.42)';for(let k=0;k<18;k++){const x=(k*53+clock*.08)%w;c.beginPath();c.moveTo(w*.5+(x-w*.5)*.2,h*.34);c.lineTo(x,h*(.55+(k%6)*.06));c.stroke();}}
 const carW=w*.23,carH=carW*.60,cx=w*.5+px*w*.19,cy=h*.78;c.fillStyle='rgba(0,0,0,.4)';c.beginPath();c.ellipse(cx,cy+carH*.25,carW*.55,carH*.14,0,0,Math.PI*2);c.fill();c.fillStyle='#050505';c.fillRect(cx-carW*.52,cy-carH*.12,carW*.16,carH*.55);c.fillRect(cx+carW*.36,cy-carH*.12,carW*.16,carH*.55);c.fillStyle=clip.meta.color||'#ffcc00';c.fillRect(cx-carW*.43,cy-carH*.3,carW*.86,carH*.63);c.fillStyle='#0a1724';c.fillRect(cx-carW*.23,cy-carH*.47,carW*.46,carH*.22);c.fillStyle=clip.meta.stripe||'#111';c.fillRect(cx-carW*.045,cy-carH*.30,carW*.09,carH*.63);if(f.nitro){c.fillStyle='#ff7a00';c.beginPath();c.moveTo(cx-carW*.2,cy+carH*.34);c.lineTo(cx-carW*.32,cy+carH*.63);c.lineTo(cx-carW*.1,cy+carH*.4);c.fill();c.beginPath();c.moveTo(cx+carW*.2,cy+carH*.34);c.lineTo(cx+carW*.32,cy+carH*.63);c.lineTo(cx+carW*.1,cy+carH*.4);c.fill();}
 c.fillStyle='rgba(2,5,10,.78)';c.fillRect(0,0,w,h*.105);c.fillRect(0,h*.89,w,h*.11);c.fillStyle='#fff';c.font='900 22px monospace';c.textAlign='center';c.fillText('RETRÔ RACER',w/2,34);c.fillStyle='#38d5ff';c.font='900 14px monospace';c.fillText(String(clip.meta.track||'').toUpperCase().slice(0,32),w/2,58);c.fillStyle='#ffcc00';c.font='900 18px monospace';c.fillText(clip.label.slice(0,34),w/2,h*.915);c.fillStyle='#fff';c.font='900 13px monospace';c.fillText(`${clip.meta.car} · ${clip.meta.code}`,w/2,h*.952);c.fillStyle='rgba(255,255,255,.55)';c.font='10px monospace';c.fillText('Clássicos dos Games · Dennys Smaniotto Pavanelli',w/2,h*.982);c.textAlign='left';}
function activeClip(){if(best)return best;const last=career.highlight?.last;if(!last)return null;return null;}
function playPreview(){const canvas=document.getElementById('highlightCanvas'),clip=activeClip();if(!canvas||!clip)return;cancelAnimationFrame(previewRaf);previewStart=performance.now();const tick=now=>{const t=(now-previewStart)% (CLIP_SECONDS*1000),idx=Math.min(clip.frames.input.length-1,Math.floor(t/1000*CLIP_HZ));renderFrame(canvas,clip,idx,now);previewRaf=requestAnimationFrame(tick);};previewRaf=requestAnimationFrame(tick);}
function setStatus(s){const e=document.getElementById('highlightStatus');if(e)e.textContent=s;}
function openHighlight(){const clip=activeClip();if(!clip){setRaceMessage('CLIPE AINDA NÃO DISPONÍVEL','#ffcc00',1);return false;}document.getElementById('highlightTitle').textContent=clip.label;document.getElementById('highlightMeta').textContent=`${clip.meta.track} · ${clip.meta.car} · ${clip.meta.code}`;showMenu('highlight');playPreview();return true;}
function stopPreview(){cancelAnimationFrame(previewRaf);previewRaf=0;}
function mimeType(){for(const t of ['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'])if(window.MediaRecorder?.isTypeSupported?.(t))return t;return'';}
async function recordWebM(){const clip=activeClip(),canvas=document.getElementById('highlightCanvas');if(!clip||!canvas||!canvas.captureStream||!window.MediaRecorder)throw new Error('WebM indisponível neste navegador.');stopPreview();const stream=canvas.captureStream(30),type=mimeType(),rec=new MediaRecorder(stream,type?{mimeType:type}:undefined),chunks=[];rec.ondataavailable=e=>{if(e.data?.size)chunks.push(e.data);};const done=new Promise((resolve,reject)=>{rec.onstop=()=>resolve(new Blob(chunks,{type:type||'video/webm'}));rec.onerror=e=>reject(e.error||new Error('Falha ao gravar'));});rec.start(250);const start=performance.now();await new Promise(resolve=>{const step=now=>{const elapsed=now-start,idx=Math.min(clip.frames.input.length-1,Math.floor(elapsed/1000*CLIP_HZ));renderFrame(canvas,clip,idx,now);if(elapsed<CLIP_SECONDS*1000)requestAnimationFrame(step);else resolve();};requestAnimationFrame(step);});rec.stop();stream.getTracks().forEach(t=>t.stop());const blob=await done;lastBlob=blob;playPreview();return blob;}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},1200);}
async function exportClip(share=false){const clip=activeClip();if(!clip)return;setStatus('RENDERIZANDO 8s…');try{const blob=await recordWebM();career.highlight.exports=(career.highlight.exports||0)+1;career.flags.c16Highlight=true;saveCareer();const file=new File([blob],`retro-racer-${String(clip.meta.level).padStart(3,'0')}-${clip.meta.code}.webm`,{type:blob.type||'video/webm'});if(share&&navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'Retrô Racer · Destaque',text:`Meu clipe ${clip.meta.code}`,files:[file]});career.highlight.shares=(career.highlight.shares||0)+1;saveCareer();setStatus('COMPARTILHADO · '+clip.meta.code);return;}downloadBlob(blob,file.name);setStatus('WEBM EXPORTADO · '+clip.meta.code);}catch(e){const canvas=document.getElementById('highlightCanvas');const url=canvas.toDataURL('image/png'),a=document.createElement('a');a.href=url;a.download=`retro-racer-${clip.meta.code}.png`;a.click();setStatus('WEBM INDISPONÍVEL · PÔSTER PNG EXPORTADO');}finally{playPreview();}}
function bind(){document.getElementById('btnHighlight')?.addEventListener('click',openHighlight);document.getElementById('btnHighlightBack')?.addEventListener('click',()=>{stopPreview();showMenu('results');});document.getElementById('btnHighlightReplay')?.addEventListener('click',playPreview);document.getElementById('btnHighlightExport')?.addEventListener('click',()=>exportClip(false));document.getElementById('btnHighlightShare')?.addEventListener('click',()=>exportClip(true));}
globalThis.highlightOpen=openHighlight;globalThis.highlightExport=exportClip;globalThis.highlightSnapshot=()=>({count,head,best:best?{kind:best.kind,label:best.label,score:best.score,frames:best.frames.input.length,code:best.meta?.code||''}:null,meta:raceMeta,exports:career.highlight?.exports||0,shares:career.highlight?.shares||0});window.RRHighlight={mark,renderFrame,open:openHighlight,recordWebM,snapshot:highlightSnapshot};bind();
