// OURO 6 — Código de Sombra: replay por inputs + seed + carro + pintura + checksum, 100% offline.
const MAX_CHAIN=4,MAX_LIBRARY=12,QR_VERSION=20,QR_SIZE=97,QR_DATA_BYTES=861,QR_ECC=28;
const te=new TextEncoder(),td=new TextDecoder(),ALPH='0123456789ABCDEFGHJKMNPQRSTVWXYZ';
let activePackage=null,lastPackage=null,sessionBest=null;
function cleanAlias(v){return String(v||'PILOTO').normalize('NFKD').replace(/[^A-Za-z0-9 _-]/g,'').trim().slice(0,16)||'PILOTO';}
function bytesToB64(bytes){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');}
function b64ToBytes(s){s=String(s||'').replaceAll('-','+').replaceAll('_','/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function fnvBytes(bytes){let h=2166136261>>>0;for(const b of bytes){h^=b;h=Math.imul(h,16777619);}return h>>>0;}
function push16(a,n){a.push(n&255,(n>>>8)&255);}function push32(a,n){a.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255);}
function read16(b,o){return b[o]|b[o+1]<<8;}function read32(b,o){return(b[o]|b[o+1]<<8|b[o+2]<<16|b[o+3]<<24)>>>0;}
function hexRgb(s){const m=String(s||'').match(/^#?([0-9a-f]{6})$/i);return m?parseInt(m[1],16):0x7be9ff;}function rgbHex(n){return'#'+(n>>>0).toString(16).padStart(6,'0').slice(-6);}
function base32(n){let s='';for(let i=0;i<7;i++){s=ALPH[n&31]+s;n=Math.floor(n/32);}return s;}
function packageCode(payload,checksum){const h2=fnvBytes(te.encode(payload));return`RR7-${base32(checksum).slice(-4)}-${base32(h2).slice(-4)}`;}
function replayBytes(replay){return b64ToBytes(replay&&replay.payload||'');}
function buildGhost(replay,lapTime){const car=currentCar(),paint=carPaint(car),skin=Math.floor(clampNumber(career.selectedSkin[car.id],0,2,0));return{level:raceLevel,seed:String(window.RRCore.rng.seed||`${raceLevel}`),car:car.id,skin,lapTime:Number(lapTime)||0,alias:cleanAlias(career.shadow.alias),color:paint.color,stripe:paint.stripe,replay:{hz:Number(replay.hz)||20,encoding:replay.encoding==='raw1'?'raw1':'rle1',sampleCount:Number(replay.sampleCount)||0,payload:replay.payload||''}};}
function encodePackage(chain){const ghosts=(chain||[]).slice(-MAX_CHAIN),a=[82,82,55,1,ghosts.length];for(const g of ghosts){const alias=te.encode(cleanAlias(g.alias)),seed=te.encode(String(g.seed||'')),rep=replayBytes(g.replay);if(alias.length>31||seed.length>96||rep.length>65535)throw new Error('Sombra excede o limite offline.');push16(a,Math.max(1,Math.min(999,Number(g.level)||1)));a.push(Math.max(0,Math.min(255,Number(g.car)||0)),Math.max(0,Math.min(2,Number(g.skin)||0)));push32(a,Math.max(1,Math.round((Number(g.lapTime)||0)*1000)));a.push(alias.length,...alias,seed.length,...seed,Math.max(1,Math.min(60,Number(g.replay&&g.replay.hz)||20)),g.replay&&g.replay.encoding==='raw1'?1:0);push16(a,Math.min(65535,Number(g.replay&&g.replay.sampleCount)||0));push16(a,rep.length);a.push(...rep);const c=hexRgb(g.color),s=hexRgb(g.stripe);a.push(c>>16&255,c>>8&255,c&255,s>>16&255,s>>8&255,s&255);}const body=Uint8Array.from(a),chk=fnvBytes(body),out=new Uint8Array(body.length+4);out.set(body);out.set([chk&255,chk>>>8&255,chk>>>16&255,chk>>>24&255],body.length);const payload=bytesToB64(out);return{v:1,chain:ghosts,payload,checksum:chk,code:packageCode(payload,chk)};}
function decodePackage(payload){const b=b64ToBytes(payload);if(b.length<10||b[0]!==82||b[1]!==82||b[2]!==55||b[3]!==1)throw new Error('Código de Sombra inválido.');const body=b.subarray(0,b.length-4),want=read32(b,b.length-4),got=fnvBytes(body);if(want!==got)throw new Error('Checksum inválido: sombra alterada ou incompleta.');let o=4,count=b[o++];if(count<1||count>MAX_CHAIN)throw new Error('Corrente de sombras inválida.');const chain=[];for(let i=0;i<count;i++){if(o+14>=body.length)throw new Error('Sombra truncada.');const level=read16(b,o);o+=2;const car=b[o++],skin=b[o++],lapTime=read32(b,o)/1000;o+=4;const al=b[o++];if(o+al>body.length)throw new Error('Apelido truncado.');const alias=cleanAlias(td.decode(b.subarray(o,o+al)));o+=al;const sl=b[o++];if(o+sl>body.length)throw new Error('Seed truncada.');const seed=td.decode(b.subarray(o,o+sl));o+=sl;const hz=b[o++],encoding=b[o++]===1?'raw1':'rle1',sampleCount=read16(b,o);o+=2;const rl=read16(b,o);o+=2;if(o+rl+6>body.length)throw new Error('Replay truncado.');const rep=b.subarray(o,o+rl);o+=rl;const color=rgbHex((b[o]<<16)|(b[o+1]<<8)|b[o+2]);o+=3;const stripe=rgbHex((b[o]<<16)|(b[o+1]<<8)|b[o+2]);o+=3;if(level<1||level>999||lapTime<=0||sampleCount>12000)throw new Error('Metadados da sombra fora do limite.');chain.push({level,car,skin,lapTime,alias,seed,color,stripe,replay:{hz,encoding,sampleCount,payload:bytesToB64(rep),format:2,bytes:rep.length}});}if(o!==body.length)throw new Error('Payload com bytes inesperados.');return{v:1,chain,payload,checksum:want,code:packageCode(payload,want)};}
function extractPayload(text){const v=String(text||'').trim();if(!v)throw new Error('Cole um link, #g= ou código RR7.');if(/^RR7-/i.test(v)){const code=v.toUpperCase();const entries=[...(career.shadow.library||[]),career.shadow.lastExport].filter(Boolean);const hit=entries.find(x=>String(x.code).toUpperCase()===code);if(!hit)throw new Error('Código curto não está neste aparelho. Compartilhe o link ou QR completo.');return hit.payload;}const m=v.match(/(?:#|[?&])g=([A-Za-z0-9_-]+)/);return m?m[1]:v.replace(/^#?g=/,'');}
function canonicalLink(pkg){const canonical=document.querySelector('link[rel="canonical"]')?.href||location.href.split('#')[0];return canonical.replace(/#.*$/,'')+'#g='+pkg.payload;}
function storeImported(pkg){if(globalThis.telemetryEvent)telemetryEvent('ghost_import',{level:Number(pkg?.chain?.[0]?.level)||0});career.shadow.library=career.shadow.library||[];career.shadow.library=career.shadow.library.filter(x=>x.code!==pkg.code);career.shadow.library.unshift({code:pkg.code,payload:pkg.payload,level:pkg.chain[0].level,alias:pkg.chain[0].alias,chain:pkg.chain.length,ghosts:pkg.chain.map(g=>({alias:g.alias,level:g.level,lapTime:g.lapTime,car:g.car}))});career.shadow.library=career.shadow.library.slice(0,MAX_LIBRARY);career.shadow.lastImport={code:pkg.code,payload:pkg.payload};career.shadow.imports=(career.shadow.imports||0)+1;career.flags.c06ShadowCode=true;saveCareer();activePackage=pkg;lastPackage=pkg;return pkg;}
function importText(text){return storeImported(decodePackage(extractPayload(text)));}
function setStatus(text,ok=true){const el=document.getElementById('shadowStatus');if(el){el.textContent=text;el.classList.toggle('bad',!ok);}}
function packageForMenu(fromResult=false){if(fromResult&&sessionBest){let chain=[];if(raceContext.mode==='shadow'&&activePackage)chain=activePackage.chain.slice(-(MAX_CHAIN-1));chain.push(sessionBest);lastPackage=encodePackage(chain);const same=career.shadow.lastExport&&career.shadow.lastExport.code===lastPackage.code;career.shadow.lastExport={code:lastPackage.code,payload:lastPackage.payload};if(!same)career.shadow.exports=(career.shadow.exports||0)+1;career.flags.c06ShadowCode=true;saveCareer();return lastPackage;}if(lastPackage)return lastPackage;for(const ref of [career.shadow.lastImport,career.shadow.lastExport])if(ref&&ref.payload){try{return(lastPackage=decodePackage(ref.payload));}catch(e){}}return null;}
function renderChain(pkg){const box=document.getElementById('shadowChain');if(!box)return;box.innerHTML='';(pkg?.chain||[]).forEach((g,i)=>{const d=document.createElement('div');d.className='shadow-chain-row';d.innerHTML=`<b>${i+1}. 👻 ${g.alias}</b><span>Fase ${String(g.level).padStart(3,'0')} · ${formatTime(g.lapTime)} · ${CARS[g.car]?.name||'CARRO'}</span>`;box.appendChild(d);});}
function drawQr(canvas,text){if(!canvas)return;const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.fillStyle='#fff';c.fillRect(0,0,canvas.width,canvas.height);try{const m=makeQrMatrixV20L(text),quiet=4,total=QR_SIZE+quiet*2,scale=Math.max(1,Math.floor(Math.min(canvas.width,canvas.height)/total)),ox=Math.floor((canvas.width-total*scale)/2),oy=Math.floor((canvas.height-total*scale)/2);c.fillStyle='#000';for(let r=0;r<QR_SIZE;r++)for(let col=0;col<QR_SIZE;col++)if(m[r][col])c.fillRect(ox+(col+quiet)*scale,oy+(r+quiet)*scale,scale,scale);canvas.dataset.qr='ok';}catch(e){c.fillStyle='#111';c.font='bold 12px monospace';c.textAlign='center';c.fillText('QR: LINK MUITO LONGO',canvas.width/2,canvas.height/2-8);c.font='10px monospace';c.fillText('USE COPIAR LINK',canvas.width/2,canvas.height/2+12);canvas.dataset.qr='long';}}
function renderMenu(fromResult=false){gameMode='shadowmenu';const pkg=packageForMenu(fromResult),alias=document.getElementById('shadowAlias');if(alias)alias.value=career.shadow.alias||'PILOTO';document.getElementById('shadowCode').textContent=pkg?pkg.code:'SEM SOMBRA GRAVADA';const link=pkg?canonicalLink(pkg):'';document.getElementById('shadowLink').value=link;renderChain(pkg);drawQr(document.getElementById('shadowQr'),pkg&&pkg.chain.length>1?canonicalLink(encodePackage([pkg.chain[pkg.chain.length-1]])):link);document.getElementById('btnShadowStart').disabled=!pkg;document.getElementById('btnShadowCopy').disabled=!pkg;document.getElementById('btnShadowShare').disabled=!pkg;setStatus(pkg?`${pkg.chain.length} sombra${pkg.chain.length>1?'s':''} · checksum OK · ${pkg.payload.length} caracteres`:'Termine uma volta para gerar sua sombra.',!!pkg);showMenu('shadow');}
async function copyLink(){if(globalThis.telemetryEvent)telemetryEvent('share_click',{kind:'shadow-copy'});const pkg=packageForMenu(false);if(!pkg)return;const link=canonicalLink(pkg);try{await navigator.clipboard.writeText(link);setStatus('LINK COPIADO · envie no WhatsApp.');}catch(e){const t=document.getElementById('shadowLink');t.focus();t.select();document.execCommand('copy');setStatus('LINK COPIADO.');}}
async function shareLink(){if(globalThis.telemetryEvent)telemetryEvent('share_click',{kind:'shadow-share'});const pkg=packageForMenu(false);if(!pkg)return;const link=canonicalLink(pkg);if(navigator.share){try{await navigator.share({title:'Retrô Racer · Código de Sombra',text:`Corra contra minha sombra ${pkg.code}`,url:link});setStatus('COMPARTILHAMENTO ABERTO.');return;}catch(e){if(e&&e.name==='AbortError')return;}}await copyLink();}
function startChallenge(){const pkg=packageForMenu(false);if(!pkg)return;activePackage=pkg;const first=pkg.chain[0];raceContext={mode:'shadow',selectedLevel:first.level,replay:false,laps:1,dailySeed:null,ghost:true,boss:false,insurance:false,shadowSeed:first.seed};openPreRace(first.level,'shadow');}
function bootPayload(){const m=location.hash.match(/^#g=([A-Za-z0-9_-]+)/);return m?m[1]:'';}
function bindUi(){document.getElementById('btnShadowCode')?.addEventListener('click',()=>renderMenu(false));document.getElementById('btnResultShadow')?.addEventListener('click',()=>renderMenu(true));document.getElementById('btnShadowBack')?.addEventListener('click',()=>{gameMode='menu';showMenu('start');});document.getElementById('btnShadowCopy')?.addEventListener('click',copyLink);document.getElementById('btnShadowShare')?.addEventListener('click',shareLink);document.getElementById('btnShadowStart')?.addEventListener('click',startChallenge);document.getElementById('btnShadowImport')?.addEventListener('click',()=>{try{const p=importText(document.getElementById('shadowImport').value);setStatus(`IMPORTADO ${p.code} · ${p.chain.length} sombra${p.chain.length>1?'s':''}`);renderMenu(false);}catch(e){setStatus(e.message||'Falha ao importar.',false);}});document.getElementById('shadowAlias')?.addEventListener('change',e=>{career.shadow.alias=cleanAlias(e.target.value);saveCareer();});}

globalThis.shadowHasBootLink=()=>!!bootPayload();
globalThis.shadowHandleBootLink=function shadowHandleBootLink(){const p=bootPayload();if(!p)return false;try{storeImported(decodePackage(p));renderMenu(false);setStatus(`DESAFIO RECEBIDO · ${activePackage.code}`);return true;}catch(e){showMenu('shadow');setStatus(e.message||'Código de Sombra inválido.',false);return false;}};
globalThis.shadowRaceStart=function shadowRaceStart(){sessionBest=null;if(window.RRCore?.lapReplay)window.RRCore.lapReplay.start({level:raceLevel,mode:raceContext.mode,seed:window.RRCore.rng.seed});};
globalThis.shadowLapComplete=function shadowLapComplete(lapTime){if(!window.RRCore?.lapReplay||!Number.isFinite(lapTime)||lapTime<5)return;const rep=window.RRCore.lapReplay.finish(),g=buildGhost(rep,lapTime);if(!sessionBest||g.lapTime<sessionBest.lapTime)sessionBest=g;window.RRCore.lapReplay.start({level:raceLevel,mode:raceContext.mode,seed:window.RRCore.rng.seed});};
globalThis.shadowGetActivePackage=()=>activePackage;
globalThis.shadowGetSharePackage=(fromResult=false)=>packageForMenu(fromResult);
globalThis.shadowBuildRaceGhosts=function shadowBuildRaceGhosts(distance){if(raceContext.mode!=='shadow'||!activePackage)return[];return activePackage.chain.filter(g=>g.level===raceLevel).slice(0,MAX_CHAIN).map(g=>({...g,samples:window.RRCore.replay.toGhostSamples(g.replay,distance,g.lapTime)}));};
globalThis.shadowOpenMenu=renderMenu;
globalThis.shadowImportText=importText;
globalThis.shadowCodec={encodePackage,decodePackage,packageCode,makeQrMatrixV20L};

// QR real, Version 20-L, Byte mode, máscara 0. Suporta até ~850 bytes do link compartilhável.
function gfTables(){const exp=new Uint16Array(512),log=new Uint16Array(256);let x=1;for(let i=0;i<255;i++){exp[i]=x;log[x]=i;x<<=1;if(x&256)x^=0x11d;}for(let i=255;i<512;i++)exp[i]=exp[i-255];return{exp,log};}const GF=gfTables();
function gfMul(a,b){return!a||!b?0:GF.exp[GF.log[a]+GF.log[b]];}
function rsGenerator(n){let p=[1];for(let i=0;i<n;i++){const q=[1,GF.exp[i]],r=new Array(p.length+1).fill(0);for(let a=0;a<p.length;a++)for(let b=0;b<2;b++)r[a+b]^=gfMul(p[a],q[b]);p=r;}return p;}
const RS_GEN=rsGenerator(QR_ECC);
function rsRemainder(data){const r=new Uint8Array(QR_ECC);for(const byte of data){const f=byte^r[0];r.copyWithin(0,1);r[QR_ECC-1]=0;if(f)for(let j=0;j<QR_ECC;j++)r[j]^=gfMul(RS_GEN[j+1],f);}return r;}
function appendBits(bits,val,len){for(let i=len-1;i>=0;i--)bits.push((val>>>i)&1);}
function qrCodewords(text){const bytes=te.encode(text);if(bytes.length>850)throw new Error('QR excede capacidade');const bits=[];appendBits(bits,4,4);appendBits(bits,bytes.length,16);for(const b of bytes)appendBits(bits,b,8);for(let i=0;i<4&&bits.length<QR_DATA_BYTES*8;i++)bits.push(0);while(bits.length%8)bits.push(0);const data=[];for(let i=0;i<bits.length;i+=8){let v=0;for(let j=0;j<8;j++)v=v<<1|(bits[i+j]||0);data.push(v);}for(let pad=0;data.length<QR_DATA_BYTES;pad++)data.push(pad%2?0x11:0xec);const sizes=[107,107,107,108,108,108,108,108],blocks=[],ecc=[];let o=0;for(const n of sizes){const d=Uint8Array.from(data.slice(o,o+n));o+=n;blocks.push(d);ecc.push(rsRemainder(d));}const out=[];for(let i=0;i<108;i++)for(const b of blocks)if(i<b.length)out.push(b[i]);for(let i=0;i<QR_ECC;i++)for(const e of ecc)out.push(e[i]);return out;}
function bchInfo(data){let d=data<<10,g=0x537;while((32-Math.clz32(d))>=(32-Math.clz32(g)))d^=g<<((32-Math.clz32(d))-(32-Math.clz32(g)));return((data<<10)|d)^0x5412;}
function bchVersion(data){let d=data<<12,g=0x1f25;while((32-Math.clz32(d))>=(32-Math.clz32(g)))d^=g<<((32-Math.clz32(d))-(32-Math.clz32(g)));return(data<<12)|d;}
function finder(m,row,col){const n=m.length;for(let r=-1;r<=7;r++)for(let c=-1;c<=7;c++){const y=row+r,x=col+c;if(y<0||y>=n||x<0||x>=n)continue;m[y][x]=r>=0&&r<=6&&c>=0&&c<=6&&(r===0||r===6||c===0||c===6||(r>=2&&r<=4&&c>=2&&c<=4));}}
function align(m,row,col){if(m[row][col]!==null)return;for(let r=-2;r<=2;r++)for(let c=-2;c<=2;c++)m[row+r][col+c]=Math.max(Math.abs(r),Math.abs(c))!==1;}
function setupType(m){const n=m.length,bits=bchInfo(8);for(let i=0;i<15;i++){const mod=((bits>>i)&1)===1;if(i<6)m[i][8]=mod;else if(i<8)m[i+1][8]=mod;else m[n-15+i][8]=mod;if(i<8)m[8][n-i-1]=mod;else if(i<9)m[8][15-i]=mod;else m[8][15-i-1]=mod;}m[n-8][8]=true;}
function setupVersion(m){const n=m.length,bits=bchVersion(QR_VERSION);for(let i=0;i<18;i++){const mod=((bits>>i)&1)===1;m[Math.floor(i/3)][i%3+n-11]=mod;m[i%3+n-11][Math.floor(i/3)]=mod;}}
export function makeQrMatrixV20L(text){const m=Array.from({length:QR_SIZE},()=>Array(QR_SIZE).fill(null));finder(m,0,0);finder(m,QR_SIZE-7,0);finder(m,0,QR_SIZE-7);for(const r of [6,34,62,90])for(const c of [6,34,62,90])align(m,r,c);for(let i=8;i<QR_SIZE-8;i++){if(m[i][6]===null)m[i][6]=(i%2===0);if(m[6][i]===null)m[6][i]=(i%2===0);}setupType(m);setupVersion(m);const data=qrCodewords(text);let row=QR_SIZE-1,inc=-1,bit=7,idx=0;for(let col=QR_SIZE-1;col>0;col-=2){if(col===6)col--;for(;;){for(let c=0;c<2;c++){const x=col-c;if(m[row][x]!==null)continue;let dark=false;if(idx<data.length)dark=((data[idx]>>>bit)&1)===1;if(((row+x)&1)===0)dark=!dark;m[row][x]=dark;bit--;if(bit<0){idx++;bit=7;}}row+=inc;if(row<0||row>=QR_SIZE){row-=inc;inc=-inc;break;}}}return m;}

bindUi();
