// CICLO 20 — telemetria local, anônima, em anel. Nenhum identificador pessoal.
const MAX=500, ALLOWED=Object.freeze({
 app_open:['day'],ftue_step:['step'],race_start:['mode','level','car'],race_finish:['mode','level','rank','time','combo','abandon'],garage_open:['car'],purchase_intent:['sku'],share_click:['kind'],ghost_import:['level'],session_end:['duration']
});
let started=performance.now(),logoTaps=0,logoTapAt=0;
function clean(name,data={}){if(!ALLOWED[name])return null;const out={};for(const k of ALLOWED[name]){const v=data[k];if(typeof v==='number'&&Number.isFinite(v))out[k]=Math.round(v*1000)/1000;else if(typeof v==='string')out[k]=v.slice(0,48);else if(typeof v==='boolean')out[k]=v;}return out;}
function day(){return localDateKey();}
function ensure(){career.telemetry=career.telemetry||structuredClone(defaultCareer.telemetry);career.telemetry.events=Array.isArray(career.telemetry.events)?career.telemetry.events:[];career.telemetry.sessionDays=Array.isArray(career.telemetry.sessionDays)?career.telemetry.sessionDays:[];return career.telemetry;}
globalThis.telemetryEvent=function telemetryEvent(name,data={}){const payload=clean(name,data);if(!payload)return false;const t=ensure(),evt={n:name,d:payload,day:day(),ts:Date.now()};t.events.push(evt);if(t.events.length>MAX)t.events.splice(0,t.events.length-MAX);if(!t.sessionDays.includes(evt.day))t.sessionDays.push(evt.day);t.sessionDays=t.sessionDays.slice(-120);saveCareer();return true;};
function startMap(){const m=new Map();for(const e of ensure().events)if(e.n==='race_start'){const k=e.d.level+'|'+e.d.mode;m.set(k,(m.get(k)||0)+1);}return m;}
function finishMap(){const m=new Map();for(const e of ensure().events)if(e.n==='race_finish'&&!e.d.abandon){const k=e.d.level+'|'+e.d.mode;m.set(k,(m.get(k)||0)+1);}return m;}
function trackRows(){const s=startMap(),f=finishMap(),rows=[];for(const [k,v] of s){const [level,mode]=k.split('|'),done=f.get(k)||0;rows.push({level:+level,mode,starts:v,finishes:done,rate:v?done/v:0});}return rows.sort((a,b)=>b.starts-a.starts).slice(0,12);}
function sessionAvg(){const a=ensure().events.filter(e=>e.n==='session_end').map(e=>e.d.duration).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:0;}
function retention(){const a=ensure().sessionDays.map(x=>Date.parse(x+'T00:00:00Z')).filter(Number.isFinite).sort((a,b)=>a-b);if(!a.length)return{d1:0,d7:0,d30:0,days:0};const first=a[0],has=n=>a.some(x=>(x-first)>=n*86400000);return{d1:has(1)?100:0,d7:has(7)?100:0,d30:has(30)?100:0,days:a.length};}
function ftue(){const es=ensure().events,steps={};for(const e of es)if(e.n==='ftue_step')steps[e.d.step]=(steps[e.d.step]||0)+1;return steps;}
function difficulty(){const buckets=Array.from({length:10},(_,i)=>({from:i*100+1,to:i===9?999:(i+1)*100,starts:0,finishes:0}));for(const r of trackRowsRaw()){const b=buckets[Math.min(9,Math.floor((r.level-1)/100))];b.starts+=r.starts;b.finishes+=r.finishes;}return buckets.map(b=>({...b,rate:b.starts?b.finishes/b.starts:0}));}
function trackRowsRaw(){const s=startMap(),f=finishMap(),rows=[];for(const [k,v] of s){const [level,mode]=k.split('|');rows.push({level:+level,mode,starts:v,finishes:f.get(k)||0});}return rows;}
globalThis.telemetrySnapshot=function telemetrySnapshot(){return{events:ensure().events.length,retention:retention(),avgSession:sessionAvg(),ftue:ftue(),tracks:trackRows(),difficulty:difficulty()};};
globalThis.telemetryFlush=async function telemetryFlush(){if(!career.settings.telemetryOptIn)return{ok:false,reason:'OPT-OUT'};const url=String(career.settings.telemetryEndpoint||'');if(!/^https:\/\//.test(url))return{ok:false,reason:'ENDPOINT'};const body=JSON.stringify({schema:1,events:ensure().events.slice(-100)});try{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body,keepalive:true});return{ok:r.ok,status:r.status};}catch(e){return{ok:false,reason:'NETWORK'};}};
function draw(){const c=document.getElementById('metricsCanvas');if(!c)return;const x=c.getContext('2d'),m=telemetrySnapshot(),W=c.width,H=c.height;x.fillStyle='#05070d';x.fillRect(0,0,W,H);x.fillStyle='#fff';x.font='bold 22px monospace';x.fillText('PAINEL LOCAL · SEM PII',28,34);x.font='14px monospace';x.fillStyle='#8ee6ff';x.fillText(`EVENTOS ${m.events} · SESSÃO MÉDIA ${m.avgSession.toFixed(1)}s · DIAS ${m.retention.days}`,28,61);x.fillStyle='#ffcc00';x.fillText(`RETORNO LOCAL  D1 ${m.retention.d1}%   D7 ${m.retention.d7}%   D30 ${m.retention.d30}%`,28,87);x.fillStyle='#fff';x.fillText('FUNIL FTUE',28,120);let y=146;for(const [k,v] of Object.entries(m.ftue).slice(0,7)){x.fillStyle='#b8c5e8';x.fillText(`${k}: ${v}`,42,y);y+=21;}x.fillStyle='#fff';x.fillText('PISTAS MAIS JOGADAS',330,120);y=146;for(const r of m.tracks.slice(0,8)){x.fillStyle=r.rate<.5?'#ff7474':'#8cff9f';x.fillText(`${String(r.level).padStart(3,'0')} ${r.mode.padEnd(10)} ${r.finishes}/${r.starts} ${Math.round(r.rate*100)}%`,344,y);y+=21;}x.fillStyle='#fff';x.fillText('CURVA DE DIFICULDADE · CONCLUSÃO',28,330);let bx=30;for(const b of m.difficulty){const h=Math.round(b.rate*120);x.fillStyle=b.rate<.5?'#ff5b66':'#49d878';x.fillRect(bx,470-h,56,h);x.fillStyle='#9ba6c5';x.font='11px monospace';x.fillText(String(b.from),bx,490);bx+=78;}}
globalThis.openMetrics=function openMetrics(){draw();gameMode='metrics';showMenu('metrics');};
function tapLogo(){const now=performance.now();if(now-logoTapAt>1600)logoTaps=0;logoTapAt=now;if(++logoTaps>=5){logoTaps=0;openMetrics();}}
function endSession(){const dur=Math.max(1,(performance.now()-started)/1000);telemetryEvent('session_end',{duration:dur});if(career.settings.telemetryOptIn)telemetryFlush();}
const brand=document.querySelector('.brand-title');if(brand)brand.addEventListener('pointerup',tapLogo);document.getElementById('btnMetricsBack')?.addEventListener('click',()=>{gameMode='menu';showMenu('start');});window.addEventListener('pagehide',endSession,{once:true});
telemetryEvent('app_open',{day:day()});career.flags.c20Telemetry=true;saveCareer();
